// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: health_record/health_record.proto

package health_record

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 健康档案总览
type HealthRecordSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PatientId          string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PatientName        string                 `protobuf:"bytes,2,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	TotalVisits        int32                  `protobuf:"varint,3,opt,name=total_visits,json=totalVisits,proto3" json:"total_visits,omitempty"`
	TotalPrescriptions int32                  `protobuf:"varint,4,opt,name=total_prescriptions,json=totalPrescriptions,proto3" json:"total_prescriptions,omitempty"`
	TotalExaminations  int32                  `protobuf:"varint,5,opt,name=total_examinations,json=totalExaminations,proto3" json:"total_examinations,omitempty"`
	Timeline           []*TimelineEvent       `protobuf:"bytes,6,rep,name=timeline,proto3" json:"timeline,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthRecordSummary) Reset() {
	*x = HealthRecordSummary{}
	mi := &file_health_record_health_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRecordSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRecordSummary) ProtoMessage() {}

func (x *HealthRecordSummary) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRecordSummary.ProtoReflect.Descriptor instead.
func (*HealthRecordSummary) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRecordSummary) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *HealthRecordSummary) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *HealthRecordSummary) GetTotalVisits() int32 {
	if x != nil {
		return x.TotalVisits
	}
	return 0
}

func (x *HealthRecordSummary) GetTotalPrescriptions() int32 {
	if x != nil {
		return x.TotalPrescriptions
	}
	return 0
}

func (x *HealthRecordSummary) GetTotalExaminations() int32 {
	if x != nil {
		return x.TotalExaminations
	}
	return 0
}

func (x *HealthRecordSummary) GetTimeline() []*TimelineEvent {
	if x != nil {
		return x.Timeline
	}
	return nil
}

// 时间轴事件
type TimelineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // visit, prescription, examination, followup
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RelatedId     string                 `protobuf:"bytes,4,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEvent) Reset() {
	*x = TimelineEvent{}
	mi := &file_health_record_health_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEvent) ProtoMessage() {}

func (x *TimelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEvent.ProtoReflect.Descriptor instead.
func (*TimelineEvent) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{1}
}

func (x *TimelineEvent) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TimelineEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TimelineEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TimelineEvent) GetRelatedId() string {
	if x != nil {
		return x.RelatedId
	}
	return ""
}

// 档案授权
type RecordAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	AuthTime      string                 `protobuf:"bytes,4,opt,name=auth_time,json=authTime,proto3" json:"auth_time,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,5,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAuthorization) Reset() {
	*x = RecordAuthorization{}
	mi := &file_health_record_health_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAuthorization) ProtoMessage() {}

func (x *RecordAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAuthorization.ProtoReflect.Descriptor instead.
func (*RecordAuthorization) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{2}
}

func (x *RecordAuthorization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordAuthorization) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *RecordAuthorization) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *RecordAuthorization) GetAuthTime() string {
	if x != nil {
		return x.AuthTime
	}
	return ""
}

func (x *RecordAuthorization) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *RecordAuthorization) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RevokeAuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAuthorizationRequest) Reset() {
	*x = RevokeAuthorizationRequest{}
	mi := &file_health_record_health_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAuthorizationRequest) ProtoMessage() {}

func (x *RevokeAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*RevokeAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeAuthorizationRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *RevokeAuthorizationRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type TimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Events        []*TimelineEvent       `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineResponse) Reset() {
	*x = TimelineResponse{}
	mi := &file_health_record_health_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineResponse) ProtoMessage() {}

func (x *TimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_record_health_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineResponse.ProtoReflect.Descriptor instead.
func (*TimelineResponse) Descriptor() ([]byte, []int) {
	return file_health_record_health_record_proto_rawDescGZIP(), []int{4}
}

func (x *TimelineResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *TimelineResponse) GetEvents() []*TimelineEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_health_record_health_record_proto protoreflect.FileDescriptor

const file_health_record_health_record_proto_rawDesc = "" +
	"\n" +
	"!health_record/health_record.proto\x12\rhealth_record\x1a\x13common/common.proto\"\x94\x02\n" +
	"\x13HealthRecordSummary\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12!\n" +
	"\fpatient_name\x18\x02 \x01(\tR\vpatientName\x12!\n" +
	"\ftotal_visits\x18\x03 \x01(\x05R\vtotalVisits\x12/\n" +
	"\x13total_prescriptions\x18\x04 \x01(\x05R\x12totalPrescriptions\x12-\n" +
	"\x12total_examinations\x18\x05 \x01(\x05R\x11totalExaminations\x128\n" +
	"\btimeline\x18\x06 \x03(\v2\x1c.health_record.TimelineEventR\btimeline\"\x83\x01\n" +
	"\rTimelineEvent\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"related_id\x18\x04 \x01(\tR\trelatedId\"\xb7\x01\n" +
	"\x13RecordAuthorization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12\x1b\n" +
	"\tauth_time\x18\x04 \x01(\tR\bauthTime\x12\x1f\n" +
	"\vexpire_time\x18\x05 \x01(\tR\n" +
	"expireTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"X\n" +
	"\x1aRevokeAuthorizationRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\tR\bdoctorId\"r\n" +
	"\x10TimelineResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x124\n" +
	"\x06events\x18\x02 \x03(\v2\x1c.health_record.TimelineEventR\x06events2\xd3\x02\n" +
	"\x13HealthRecordService\x12C\n" +
	"\n" +
	"GetSummary\x12\x11.common.IdRequest\x1a\".health_record.HealthRecordSummary\x12A\n" +
	"\vGetTimeline\x12\x11.common.IdRequest\x1a\x1f.health_record.TimelineResponse\x12\\\n" +
	"\x12GrantAuthorization\x12\".health_record.RecordAuthorization\x1a\".health_record.RecordAuthorization\x12V\n" +
	"\x13RevokeAuthorization\x12).health_record.RevokeAuthorizationRequest\x1a\x14.common.BaseResponseB Z\x1ehis-go/api/proto/health_recordb\x06proto3"

var (
	file_health_record_health_record_proto_rawDescOnce sync.Once
	file_health_record_health_record_proto_rawDescData []byte
)

func file_health_record_health_record_proto_rawDescGZIP() []byte {
	file_health_record_health_record_proto_rawDescOnce.Do(func() {
		file_health_record_health_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_record_health_record_proto_rawDesc), len(file_health_record_health_record_proto_rawDesc)))
	})
	return file_health_record_health_record_proto_rawDescData
}

var file_health_record_health_record_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_health_record_health_record_proto_goTypes = []any{
	(*HealthRecordSummary)(nil),        // 0: health_record.HealthRecordSummary
	(*TimelineEvent)(nil),              // 1: health_record.TimelineEvent
	(*RecordAuthorization)(nil),        // 2: health_record.RecordAuthorization
	(*RevokeAuthorizationRequest)(nil), // 3: health_record.RevokeAuthorizationRequest
	(*TimelineResponse)(nil),           // 4: health_record.TimelineResponse
	(*common.BaseResponse)(nil),        // 5: common.BaseResponse
	(*common.IdRequest)(nil),           // 6: common.IdRequest
}
var file_health_record_health_record_proto_depIdxs = []int32{
	1, // 0: health_record.HealthRecordSummary.timeline:type_name -> health_record.TimelineEvent
	5, // 1: health_record.TimelineResponse.base:type_name -> common.BaseResponse
	1, // 2: health_record.TimelineResponse.events:type_name -> health_record.TimelineEvent
	6, // 3: health_record.HealthRecordService.GetSummary:input_type -> common.IdRequest
	6, // 4: health_record.HealthRecordService.GetTimeline:input_type -> common.IdRequest
	2, // 5: health_record.HealthRecordService.GrantAuthorization:input_type -> health_record.RecordAuthorization
	3, // 6: health_record.HealthRecordService.RevokeAuthorization:input_type -> health_record.RevokeAuthorizationRequest
	0, // 7: health_record.HealthRecordService.GetSummary:output_type -> health_record.HealthRecordSummary
	4, // 8: health_record.HealthRecordService.GetTimeline:output_type -> health_record.TimelineResponse
	2, // 9: health_record.HealthRecordService.GrantAuthorization:output_type -> health_record.RecordAuthorization
	5, // 10: health_record.HealthRecordService.RevokeAuthorization:output_type -> common.BaseResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_health_record_health_record_proto_init() }
func file_health_record_health_record_proto_init() {
	if File_health_record_health_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_record_health_record_proto_rawDesc), len(file_health_record_health_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_record_health_record_proto_goTypes,
		DependencyIndexes: file_health_record_health_record_proto_depIdxs,
		MessageInfos:      file_health_record_health_record_proto_msgTypes,
	}.Build()
	File_health_record_health_record_proto = out.File
	file_health_record_health_record_proto_goTypes = nil
	file_health_record_health_record_proto_depIdxs = nil
}
