// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: inpatient/inpatient.proto

package inpatient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 住院记录
type InpatientRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PatientName   string                 `protobuf:"bytes,3,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	AdmissionDate string                 `protobuf:"bytes,4,opt,name=admission_date,json=admissionDate,proto3" json:"admission_date,omitempty"`
	DischargeDate string                 `protobuf:"bytes,5,opt,name=discharge_date,json=dischargeDate,proto3" json:"discharge_date,omitempty"`
	DeptId        string                 `protobuf:"bytes,6,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	RoomNo        string                 `protobuf:"bytes,7,opt,name=room_no,json=roomNo,proto3" json:"room_no,omitempty"`
	BedNo         string                 `protobuf:"bytes,8,opt,name=bed_no,json=bedNo,proto3" json:"bed_no,omitempty"`
	Diagnosis     string                 `protobuf:"bytes,9,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	Deposit       float64                `protobuf:"fixed64,10,opt,name=deposit,proto3" json:"deposit,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,11,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Status        int32                  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"` // 0-待入院 1-住院中 2-已出院
	Orders        []*MedicalOrder        `protobuf:"bytes,13,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InpatientRecord) Reset() {
	*x = InpatientRecord{}
	mi := &file_inpatient_inpatient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InpatientRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InpatientRecord) ProtoMessage() {}

func (x *InpatientRecord) ProtoReflect() protoreflect.Message {
	mi := &file_inpatient_inpatient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InpatientRecord.ProtoReflect.Descriptor instead.
func (*InpatientRecord) Descriptor() ([]byte, []int) {
	return file_inpatient_inpatient_proto_rawDescGZIP(), []int{0}
}

func (x *InpatientRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InpatientRecord) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *InpatientRecord) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *InpatientRecord) GetAdmissionDate() string {
	if x != nil {
		return x.AdmissionDate
	}
	return ""
}

func (x *InpatientRecord) GetDischargeDate() string {
	if x != nil {
		return x.DischargeDate
	}
	return ""
}

func (x *InpatientRecord) GetDeptId() string {
	if x != nil {
		return x.DeptId
	}
	return ""
}

func (x *InpatientRecord) GetRoomNo() string {
	if x != nil {
		return x.RoomNo
	}
	return ""
}

func (x *InpatientRecord) GetBedNo() string {
	if x != nil {
		return x.BedNo
	}
	return ""
}

func (x *InpatientRecord) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *InpatientRecord) GetDeposit() float64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *InpatientRecord) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *InpatientRecord) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InpatientRecord) GetOrders() []*MedicalOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

// 医嘱
type MedicalOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InpatientId   string                 `protobuf:"bytes,2,opt,name=inpatient_id,json=inpatientId,proto3" json:"inpatient_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	OrderType     int32                  `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"` // 1-长期医嘱 2-临时医嘱
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	StartTime     string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedicalOrder) Reset() {
	*x = MedicalOrder{}
	mi := &file_inpatient_inpatient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedicalOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedicalOrder) ProtoMessage() {}

func (x *MedicalOrder) ProtoReflect() protoreflect.Message {
	mi := &file_inpatient_inpatient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedicalOrder.ProtoReflect.Descriptor instead.
func (*MedicalOrder) Descriptor() ([]byte, []int) {
	return file_inpatient_inpatient_proto_rawDescGZIP(), []int{1}
}

func (x *MedicalOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MedicalOrder) GetInpatientId() string {
	if x != nil {
		return x.InpatientId
	}
	return ""
}

func (x *MedicalOrder) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *MedicalOrder) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *MedicalOrder) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MedicalOrder) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *MedicalOrder) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *MedicalOrder) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 护理记录
type NursingRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InpatientId   string                 `protobuf:"bytes,2,opt,name=inpatient_id,json=inpatientId,proto3" json:"inpatient_id,omitempty"`
	NurseId       string                 `protobuf:"bytes,3,opt,name=nurse_id,json=nurseId,proto3" json:"nurse_id,omitempty"`
	RecordTime    string                 `protobuf:"bytes,4,opt,name=record_time,json=recordTime,proto3" json:"record_time,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	VitalSigns    string                 `protobuf:"bytes,6,opt,name=vital_signs,json=vitalSigns,proto3" json:"vital_signs,omitempty"` // 生命体征 JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NursingRecord) Reset() {
	*x = NursingRecord{}
	mi := &file_inpatient_inpatient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NursingRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NursingRecord) ProtoMessage() {}

func (x *NursingRecord) ProtoReflect() protoreflect.Message {
	mi := &file_inpatient_inpatient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NursingRecord.ProtoReflect.Descriptor instead.
func (*NursingRecord) Descriptor() ([]byte, []int) {
	return file_inpatient_inpatient_proto_rawDescGZIP(), []int{2}
}

func (x *NursingRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NursingRecord) GetInpatientId() string {
	if x != nil {
		return x.InpatientId
	}
	return ""
}

func (x *NursingRecord) GetNurseId() string {
	if x != nil {
		return x.NurseId
	}
	return ""
}

func (x *NursingRecord) GetRecordTime() string {
	if x != nil {
		return x.RecordTime
	}
	return ""
}

func (x *NursingRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NursingRecord) GetVitalSigns() string {
	if x != nil {
		return x.VitalSigns
	}
	return ""
}

type AdmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DeptId        string                 `protobuf:"bytes,2,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	RoomNo        string                 `protobuf:"bytes,3,opt,name=room_no,json=roomNo,proto3" json:"room_no,omitempty"`
	BedNo         string                 `protobuf:"bytes,4,opt,name=bed_no,json=bedNo,proto3" json:"bed_no,omitempty"`
	Diagnosis     string                 `protobuf:"bytes,5,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	Deposit       float64                `protobuf:"fixed64,6,opt,name=deposit,proto3" json:"deposit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitRequest) Reset() {
	*x = AdmitRequest{}
	mi := &file_inpatient_inpatient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitRequest) ProtoMessage() {}

func (x *AdmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inpatient_inpatient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitRequest.ProtoReflect.Descriptor instead.
func (*AdmitRequest) Descriptor() ([]byte, []int) {
	return file_inpatient_inpatient_proto_rawDescGZIP(), []int{3}
}

func (x *AdmitRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AdmitRequest) GetDeptId() string {
	if x != nil {
		return x.DeptId
	}
	return ""
}

func (x *AdmitRequest) GetRoomNo() string {
	if x != nil {
		return x.RoomNo
	}
	return ""
}

func (x *AdmitRequest) GetBedNo() string {
	if x != nil {
		return x.BedNo
	}
	return ""
}

func (x *AdmitRequest) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *AdmitRequest) GetDeposit() float64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

type InpatientListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	DeptId        string                 `protobuf:"bytes,2,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InpatientListRequest) Reset() {
	*x = InpatientListRequest{}
	mi := &file_inpatient_inpatient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InpatientListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InpatientListRequest) ProtoMessage() {}

func (x *InpatientListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inpatient_inpatient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InpatientListRequest.ProtoReflect.Descriptor instead.
func (*InpatientListRequest) Descriptor() ([]byte, []int) {
	return file_inpatient_inpatient_proto_rawDescGZIP(), []int{4}
}

func (x *InpatientListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *InpatientListRequest) GetDeptId() string {
	if x != nil {
		return x.DeptId
	}
	return ""
}

func (x *InpatientListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type InpatientListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Records       []*InpatientRecord     `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InpatientListResponse) Reset() {
	*x = InpatientListResponse{}
	mi := &file_inpatient_inpatient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InpatientListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InpatientListResponse) ProtoMessage() {}

func (x *InpatientListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inpatient_inpatient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InpatientListResponse.ProtoReflect.Descriptor instead.
func (*InpatientListResponse) Descriptor() ([]byte, []int) {
	return file_inpatient_inpatient_proto_rawDescGZIP(), []int{5}
}

func (x *InpatientListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *InpatientListResponse) GetRecords() []*InpatientRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *InpatientListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_inpatient_inpatient_proto protoreflect.FileDescriptor

const file_inpatient_inpatient_proto_rawDesc = "" +
	"\n" +
	"\x19inpatient/inpatient.proto\x12\tinpatient\x1a\x13common/common.proto\"\x9a\x03\n" +
	"\x0fInpatientRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12!\n" +
	"\fpatient_name\x18\x03 \x01(\tR\vpatientName\x12%\n" +
	"\x0eadmission_date\x18\x04 \x01(\tR\radmissionDate\x12%\n" +
	"\x0edischarge_date\x18\x05 \x01(\tR\rdischargeDate\x12\x17\n" +
	"\adept_id\x18\x06 \x01(\tR\x06deptId\x12\x17\n" +
	"\aroom_no\x18\a \x01(\tR\x06roomNo\x12\x15\n" +
	"\x06bed_no\x18\b \x01(\tR\x05bedNo\x12\x1c\n" +
	"\tdiagnosis\x18\t \x01(\tR\tdiagnosis\x12\x18\n" +
	"\adeposit\x18\n" +
	" \x01(\x01R\adeposit\x12\x1d\n" +
	"\n" +
	"total_cost\x18\v \x01(\x01R\ttotalCost\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\x12/\n" +
	"\x06orders\x18\r \x03(\v2\x17.inpatient.MedicalOrderR\x06orders\"\xe9\x01\n" +
	"\fMedicalOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\finpatient_id\x18\x02 \x01(\tR\vinpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12\x1d\n" +
	"\n" +
	"order_type\x18\x04 \x01(\x05R\torderType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\"\xb9\x01\n" +
	"\rNursingRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\finpatient_id\x18\x02 \x01(\tR\vinpatientId\x12\x19\n" +
	"\bnurse_id\x18\x03 \x01(\tR\anurseId\x12\x1f\n" +
	"\vrecord_time\x18\x04 \x01(\tR\n" +
	"recordTime\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1f\n" +
	"\vvital_signs\x18\x06 \x01(\tR\n" +
	"vitalSigns\"\xae\x01\n" +
	"\fAdmitRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x17\n" +
	"\adept_id\x18\x02 \x01(\tR\x06deptId\x12\x17\n" +
	"\aroom_no\x18\x03 \x01(\tR\x06roomNo\x12\x15\n" +
	"\x06bed_no\x18\x04 \x01(\tR\x05bedNo\x12\x1c\n" +
	"\tdiagnosis\x18\x05 \x01(\tR\tdiagnosis\x12\x18\n" +
	"\adeposit\x18\x06 \x01(\x01R\adeposit\"p\n" +
	"\x14InpatientListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x17\n" +
	"\adept_id\x18\x02 \x01(\tR\x06deptId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\xa1\x01\n" +
	"\x15InpatientListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x124\n" +
	"\arecords\x18\x02 \x03(\v2\x1a.inpatient.InpatientRecordR\arecords\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page2\xc1\x03\n" +
	"\x10InpatientService\x12C\n" +
	"\fAdmitPatient\x12\x17.inpatient.AdmitRequest\x1a\x1a.inpatient.InpatientRecord\x12A\n" +
	"\x10DischargePatient\x12\x11.common.IdRequest\x1a\x1a.inpatient.InpatientRecord\x12=\n" +
	"\fGetInpatient\x12\x11.common.IdRequest\x1a\x1a.inpatient.InpatientRecord\x12F\n" +
	"\x12CreateMedicalOrder\x12\x17.inpatient.MedicalOrder\x1a\x17.inpatient.MedicalOrder\x12I\n" +
	"\x13CreateNursingRecord\x12\x18.inpatient.NursingRecord\x1a\x18.inpatient.NursingRecord\x12S\n" +
	"\x0eListInpatients\x12\x1f.inpatient.InpatientListRequest\x1a .inpatient.InpatientListResponseB\x1cZ\x1ahis-go/api/proto/inpatientb\x06proto3"

var (
	file_inpatient_inpatient_proto_rawDescOnce sync.Once
	file_inpatient_inpatient_proto_rawDescData []byte
)

func file_inpatient_inpatient_proto_rawDescGZIP() []byte {
	file_inpatient_inpatient_proto_rawDescOnce.Do(func() {
		file_inpatient_inpatient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inpatient_inpatient_proto_rawDesc), len(file_inpatient_inpatient_proto_rawDesc)))
	})
	return file_inpatient_inpatient_proto_rawDescData
}

var file_inpatient_inpatient_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inpatient_inpatient_proto_goTypes = []any{
	(*InpatientRecord)(nil),       // 0: inpatient.InpatientRecord
	(*MedicalOrder)(nil),          // 1: inpatient.MedicalOrder
	(*NursingRecord)(nil),         // 2: inpatient.NursingRecord
	(*AdmitRequest)(nil),          // 3: inpatient.AdmitRequest
	(*InpatientListRequest)(nil),  // 4: inpatient.InpatientListRequest
	(*InpatientListResponse)(nil), // 5: inpatient.InpatientListResponse
	(*common.PageRequest)(nil),    // 6: common.PageRequest
	(*common.BaseResponse)(nil),   // 7: common.BaseResponse
	(*common.PageResponse)(nil),   // 8: common.PageResponse
	(*common.IdRequest)(nil),      // 9: common.IdRequest
}
var file_inpatient_inpatient_proto_depIdxs = []int32{
	1,  // 0: inpatient.InpatientRecord.orders:type_name -> inpatient.MedicalOrder
	6,  // 1: inpatient.InpatientListRequest.page:type_name -> common.PageRequest
	7,  // 2: inpatient.InpatientListResponse.base:type_name -> common.BaseResponse
	0,  // 3: inpatient.InpatientListResponse.records:type_name -> inpatient.InpatientRecord
	8,  // 4: inpatient.InpatientListResponse.page:type_name -> common.PageResponse
	3,  // 5: inpatient.InpatientService.AdmitPatient:input_type -> inpatient.AdmitRequest
	9,  // 6: inpatient.InpatientService.DischargePatient:input_type -> common.IdRequest
	9,  // 7: inpatient.InpatientService.GetInpatient:input_type -> common.IdRequest
	1,  // 8: inpatient.InpatientService.CreateMedicalOrder:input_type -> inpatient.MedicalOrder
	2,  // 9: inpatient.InpatientService.CreateNursingRecord:input_type -> inpatient.NursingRecord
	4,  // 10: inpatient.InpatientService.ListInpatients:input_type -> inpatient.InpatientListRequest
	0,  // 11: inpatient.InpatientService.AdmitPatient:output_type -> inpatient.InpatientRecord
	0,  // 12: inpatient.InpatientService.DischargePatient:output_type -> inpatient.InpatientRecord
	0,  // 13: inpatient.InpatientService.GetInpatient:output_type -> inpatient.InpatientRecord
	1,  // 14: inpatient.InpatientService.CreateMedicalOrder:output_type -> inpatient.MedicalOrder
	2,  // 15: inpatient.InpatientService.CreateNursingRecord:output_type -> inpatient.NursingRecord
	5,  // 16: inpatient.InpatientService.ListInpatients:output_type -> inpatient.InpatientListResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_inpatient_inpatient_proto_init() }
func file_inpatient_inpatient_proto_init() {
	if File_inpatient_inpatient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inpatient_inpatient_proto_rawDesc), len(file_inpatient_inpatient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inpatient_inpatient_proto_goTypes,
		DependencyIndexes: file_inpatient_inpatient_proto_depIdxs,
		MessageInfos:      file_inpatient_inpatient_proto_msgTypes,
	}.Build()
	File_inpatient_inpatient_proto = out.File
	file_inpatient_inpatient_proto_goTypes = nil
	file_inpatient_inpatient_proto_depIdxs = nil
}
