// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: inpatient/inpatient.proto

package inpatient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "his-go/api/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InpatientService_AdmitPatient_FullMethodName        = "/inpatient.InpatientService/AdmitPatient"
	InpatientService_DischargePatient_FullMethodName    = "/inpatient.InpatientService/DischargePatient"
	InpatientService_GetInpatient_FullMethodName        = "/inpatient.InpatientService/GetInpatient"
	InpatientService_CreateMedicalOrder_FullMethodName  = "/inpatient.InpatientService/CreateMedicalOrder"
	InpatientService_CreateNursingRecord_FullMethodName = "/inpatient.InpatientService/CreateNursingRecord"
	InpatientService_ListInpatients_FullMethodName      = "/inpatient.InpatientService/ListInpatients"
)

// InpatientServiceClient is the client API for InpatientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 住院服务
type InpatientServiceClient interface {
	AdmitPatient(ctx context.Context, in *AdmitRequest, opts ...grpc.CallOption) (*InpatientRecord, error)
	DischargePatient(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*InpatientRecord, error)
	GetInpatient(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*InpatientRecord, error)
	CreateMedicalOrder(ctx context.Context, in *MedicalOrder, opts ...grpc.CallOption) (*MedicalOrder, error)
	CreateNursingRecord(ctx context.Context, in *NursingRecord, opts ...grpc.CallOption) (*NursingRecord, error)
	ListInpatients(ctx context.Context, in *InpatientListRequest, opts ...grpc.CallOption) (*InpatientListResponse, error)
}

type inpatientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInpatientServiceClient(cc grpc.ClientConnInterface) InpatientServiceClient {
	return &inpatientServiceClient{cc}
}

func (c *inpatientServiceClient) AdmitPatient(ctx context.Context, in *AdmitRequest, opts ...grpc.CallOption) (*InpatientRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InpatientRecord)
	err := c.cc.Invoke(ctx, InpatientService_AdmitPatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inpatientServiceClient) DischargePatient(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*InpatientRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InpatientRecord)
	err := c.cc.Invoke(ctx, InpatientService_DischargePatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inpatientServiceClient) GetInpatient(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*InpatientRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InpatientRecord)
	err := c.cc.Invoke(ctx, InpatientService_GetInpatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inpatientServiceClient) CreateMedicalOrder(ctx context.Context, in *MedicalOrder, opts ...grpc.CallOption) (*MedicalOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MedicalOrder)
	err := c.cc.Invoke(ctx, InpatientService_CreateMedicalOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inpatientServiceClient) CreateNursingRecord(ctx context.Context, in *NursingRecord, opts ...grpc.CallOption) (*NursingRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NursingRecord)
	err := c.cc.Invoke(ctx, InpatientService_CreateNursingRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inpatientServiceClient) ListInpatients(ctx context.Context, in *InpatientListRequest, opts ...grpc.CallOption) (*InpatientListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InpatientListResponse)
	err := c.cc.Invoke(ctx, InpatientService_ListInpatients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InpatientServiceServer is the server API for InpatientService service.
// All implementations must embed UnimplementedInpatientServiceServer
// for forward compatibility.
//
// 住院服务
type InpatientServiceServer interface {
	AdmitPatient(context.Context, *AdmitRequest) (*InpatientRecord, error)
	DischargePatient(context.Context, *common.IdRequest) (*InpatientRecord, error)
	GetInpatient(context.Context, *common.IdRequest) (*InpatientRecord, error)
	CreateMedicalOrder(context.Context, *MedicalOrder) (*MedicalOrder, error)
	CreateNursingRecord(context.Context, *NursingRecord) (*NursingRecord, error)
	ListInpatients(context.Context, *InpatientListRequest) (*InpatientListResponse, error)
	mustEmbedUnimplementedInpatientServiceServer()
}

// UnimplementedInpatientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInpatientServiceServer struct{}

func (UnimplementedInpatientServiceServer) AdmitPatient(context.Context, *AdmitRequest) (*InpatientRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method AdmitPatient not implemented")
}
func (UnimplementedInpatientServiceServer) DischargePatient(context.Context, *common.IdRequest) (*InpatientRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method DischargePatient not implemented")
}
func (UnimplementedInpatientServiceServer) GetInpatient(context.Context, *common.IdRequest) (*InpatientRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInpatient not implemented")
}
func (UnimplementedInpatientServiceServer) CreateMedicalOrder(context.Context, *MedicalOrder) (*MedicalOrder, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMedicalOrder not implemented")
}
func (UnimplementedInpatientServiceServer) CreateNursingRecord(context.Context, *NursingRecord) (*NursingRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNursingRecord not implemented")
}
func (UnimplementedInpatientServiceServer) ListInpatients(context.Context, *InpatientListRequest) (*InpatientListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInpatients not implemented")
}
func (UnimplementedInpatientServiceServer) mustEmbedUnimplementedInpatientServiceServer() {}
func (UnimplementedInpatientServiceServer) testEmbeddedByValue()                          {}

// UnsafeInpatientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InpatientServiceServer will
// result in compilation errors.
type UnsafeInpatientServiceServer interface {
	mustEmbedUnimplementedInpatientServiceServer()
}

func RegisterInpatientServiceServer(s grpc.ServiceRegistrar, srv InpatientServiceServer) {
	// If the following call panics, it indicates UnimplementedInpatientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InpatientService_ServiceDesc, srv)
}

func _InpatientService_AdmitPatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InpatientServiceServer).AdmitPatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InpatientService_AdmitPatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InpatientServiceServer).AdmitPatient(ctx, req.(*AdmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InpatientService_DischargePatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InpatientServiceServer).DischargePatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InpatientService_DischargePatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InpatientServiceServer).DischargePatient(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InpatientService_GetInpatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InpatientServiceServer).GetInpatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InpatientService_GetInpatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InpatientServiceServer).GetInpatient(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InpatientService_CreateMedicalOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MedicalOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InpatientServiceServer).CreateMedicalOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InpatientService_CreateMedicalOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InpatientServiceServer).CreateMedicalOrder(ctx, req.(*MedicalOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _InpatientService_CreateNursingRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NursingRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InpatientServiceServer).CreateNursingRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InpatientService_CreateNursingRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InpatientServiceServer).CreateNursingRecord(ctx, req.(*NursingRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _InpatientService_ListInpatients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InpatientListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InpatientServiceServer).ListInpatients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InpatientService_ListInpatients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InpatientServiceServer).ListInpatients(ctx, req.(*InpatientListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InpatientService_ServiceDesc is the grpc.ServiceDesc for InpatientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InpatientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inpatient.InpatientService",
	HandlerType: (*InpatientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdmitPatient",
			Handler:    _InpatientService_AdmitPatient_Handler,
		},
		{
			MethodName: "DischargePatient",
			Handler:    _InpatientService_DischargePatient_Handler,
		},
		{
			MethodName: "GetInpatient",
			Handler:    _InpatientService_GetInpatient_Handler,
		},
		{
			MethodName: "CreateMedicalOrder",
			Handler:    _InpatientService_CreateMedicalOrder_Handler,
		},
		{
			MethodName: "CreateNursingRecord",
			Handler:    _InpatientService_CreateNursingRecord_Handler,
		},
		{
			MethodName: "ListInpatients",
			Handler:    _InpatientService_ListInpatients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inpatient/inpatient.proto",
}
