// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 患者信息
type PatientInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IdCard         string                 `protobuf:"bytes,3,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Phone          string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender         string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Age            int32                  `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	Address        string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	AllergyHistory string                 `protobuf:"bytes,8,opt,name=allergy_history,json=allergyHistory,proto3" json:"allergy_history,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PatientInfo) Reset() {
	*x = PatientInfo{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientInfo) ProtoMessage() {}

func (x *PatientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientInfo.ProtoReflect.Descriptor instead.
func (*PatientInfo) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *PatientInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatientInfo) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *PatientInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PatientInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PatientInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PatientInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PatientInfo) GetAllergyHistory() string {
	if x != nil {
		return x.AllergyHistory
	}
	return ""
}

func (x *PatientInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PatientInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 患者列表请求
type PatientListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	IdCard        string                 `protobuf:"bytes,4,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientListRequest) Reset() {
	*x = PatientListRequest{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientListRequest) ProtoMessage() {}

func (x *PatientListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientListRequest.ProtoReflect.Descriptor instead.
func (*PatientListRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *PatientListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PatientListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatientListRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PatientListRequest) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

// 患者列表响应
type PatientListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Patients      []*PatientInfo         `protobuf:"bytes,2,rep,name=patients,proto3" json:"patients,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientListResponse) Reset() {
	*x = PatientListResponse{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientListResponse) ProtoMessage() {}

func (x *PatientListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientListResponse.ProtoReflect.Descriptor instead.
func (*PatientListResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *PatientListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PatientListResponse) GetPatients() []*PatientInfo {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *PatientListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// 科室信息
type DepartmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentInfo) Reset() {
	*x = DepartmentInfo{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentInfo) ProtoMessage() {}

func (x *DepartmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentInfo.ProtoReflect.Descriptor instead.
func (*DepartmentInfo) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *DepartmentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DepartmentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentInfo) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *DepartmentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DepartmentInfo) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// 员工信息
type EmployeeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	DeptId        string                 `protobuf:"bytes,4,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Specialty     string                 `protobuf:"bytes,6,opt,name=specialty,proto3" json:"specialty,omitempty"`
	Introduction  string                 `protobuf:"bytes,7,opt,name=introduction,proto3" json:"introduction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeInfo) Reset() {
	*x = EmployeeInfo{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeInfo) ProtoMessage() {}

func (x *EmployeeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeInfo.ProtoReflect.Descriptor instead.
func (*EmployeeInfo) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *EmployeeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmployeeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmployeeInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *EmployeeInfo) GetDeptId() string {
	if x != nil {
		return x.DeptId
	}
	return ""
}

func (x *EmployeeInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EmployeeInfo) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *EmployeeInfo) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

type DepartmentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Departments   []*DepartmentInfo      `protobuf:"bytes,2,rep,name=departments,proto3" json:"departments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentListResponse) Reset() {
	*x = DepartmentListResponse{}
	mi := &file_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentListResponse) ProtoMessage() {}

func (x *DepartmentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentListResponse.ProtoReflect.Descriptor instead.
func (*DepartmentListResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *DepartmentListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DepartmentListResponse) GetDepartments() []*DepartmentInfo {
	if x != nil {
		return x.Departments
	}
	return nil
}

type EmployeeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	DeptId        string                 `protobuf:"bytes,2,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeListRequest) Reset() {
	*x = EmployeeListRequest{}
	mi := &file_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeListRequest) ProtoMessage() {}

func (x *EmployeeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeListRequest.ProtoReflect.Descriptor instead.
func (*EmployeeListRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *EmployeeListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *EmployeeListRequest) GetDeptId() string {
	if x != nil {
		return x.DeptId
	}
	return ""
}

func (x *EmployeeListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EmployeeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Employees     []*EmployeeInfo        `protobuf:"bytes,2,rep,name=employees,proto3" json:"employees,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeListResponse) Reset() {
	*x = EmployeeListResponse{}
	mi := &file_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeListResponse) ProtoMessage() {}

func (x *EmployeeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeListResponse.ProtoReflect.Descriptor instead.
func (*EmployeeListResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *EmployeeListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *EmployeeListResponse) GetEmployees() []*EmployeeInfo {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *EmployeeListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\x1a\x13common/common.proto\"\x8b\x02\n" +
	"\vPatientInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aid_card\x18\x03 \x01(\tR\x06idCard\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x10\n" +
	"\x03age\x18\x06 \x01(\x05R\x03age\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12'\n" +
	"\x0fallergy_history\x18\b \x01(\tR\x0eallergyHistory\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\x80\x01\n" +
	"\x12PatientListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x17\n" +
	"\aid_card\x18\x04 \x01(\tR\x06idCard\"\x98\x01\n" +
	"\x13PatientListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12-\n" +
	"\bpatients\x18\x02 \x03(\v2\x11.user.PatientInfoR\bpatients\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page\"\x92\x01\n" +
	"\x0eDepartmentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\"\xb9\x01\n" +
	"\fEmployeeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x17\n" +
	"\adept_id\x18\x04 \x01(\tR\x06deptId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1c\n" +
	"\tspecialty\x18\x06 \x01(\tR\tspecialty\x12\"\n" +
	"\fintroduction\x18\a \x01(\tR\fintroduction\"z\n" +
	"\x16DepartmentListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x126\n" +
	"\vdepartments\x18\x02 \x03(\v2\x14.user.DepartmentInfoR\vdepartments\"k\n" +
	"\x13EmployeeListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x17\n" +
	"\adept_id\x18\x02 \x01(\tR\x06deptId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x9c\x01\n" +
	"\x14EmployeeListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x120\n" +
	"\temployees\x18\x02 \x03(\v2\x12.user.EmployeeInfoR\temployees\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page2\xb2\x03\n" +
	"\vUserService\x122\n" +
	"\n" +
	"GetPatient\x12\x11.common.IdRequest\x1a\x11.user.PatientInfo\x12C\n" +
	"\fListPatients\x12\x18.user.PatientListRequest\x1a\x19.user.PatientListResponse\x125\n" +
	"\rCreatePatient\x12\x11.user.PatientInfo\x1a\x11.user.PatientInfo\x125\n" +
	"\rUpdatePatient\x12\x11.user.PatientInfo\x1a\x11.user.PatientInfo\x12>\n" +
	"\x0fListDepartments\x12\r.common.Empty\x1a\x1c.user.DepartmentListResponse\x124\n" +
	"\vGetEmployee\x12\x11.common.IdRequest\x1a\x12.user.EmployeeInfo\x12F\n" +
	"\rListEmployees\x12\x19.user.EmployeeListRequest\x1a\x1a.user.EmployeeListResponseB\x17Z\x15his-go/api/proto/userb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_user_proto_goTypes = []any{
	(*PatientInfo)(nil),            // 0: user.PatientInfo
	(*PatientListRequest)(nil),     // 1: user.PatientListRequest
	(*PatientListResponse)(nil),    // 2: user.PatientListResponse
	(*DepartmentInfo)(nil),         // 3: user.DepartmentInfo
	(*EmployeeInfo)(nil),           // 4: user.EmployeeInfo
	(*DepartmentListResponse)(nil), // 5: user.DepartmentListResponse
	(*EmployeeListRequest)(nil),    // 6: user.EmployeeListRequest
	(*EmployeeListResponse)(nil),   // 7: user.EmployeeListResponse
	(*common.PageRequest)(nil),     // 8: common.PageRequest
	(*common.BaseResponse)(nil),    // 9: common.BaseResponse
	(*common.PageResponse)(nil),    // 10: common.PageResponse
	(*common.IdRequest)(nil),       // 11: common.IdRequest
	(*common.Empty)(nil),           // 12: common.Empty
}
var file_user_user_proto_depIdxs = []int32{
	8,  // 0: user.PatientListRequest.page:type_name -> common.PageRequest
	9,  // 1: user.PatientListResponse.base:type_name -> common.BaseResponse
	0,  // 2: user.PatientListResponse.patients:type_name -> user.PatientInfo
	10, // 3: user.PatientListResponse.page:type_name -> common.PageResponse
	9,  // 4: user.DepartmentListResponse.base:type_name -> common.BaseResponse
	3,  // 5: user.DepartmentListResponse.departments:type_name -> user.DepartmentInfo
	8,  // 6: user.EmployeeListRequest.page:type_name -> common.PageRequest
	9,  // 7: user.EmployeeListResponse.base:type_name -> common.BaseResponse
	4,  // 8: user.EmployeeListResponse.employees:type_name -> user.EmployeeInfo
	10, // 9: user.EmployeeListResponse.page:type_name -> common.PageResponse
	11, // 10: user.UserService.GetPatient:input_type -> common.IdRequest
	1,  // 11: user.UserService.ListPatients:input_type -> user.PatientListRequest
	0,  // 12: user.UserService.CreatePatient:input_type -> user.PatientInfo
	0,  // 13: user.UserService.UpdatePatient:input_type -> user.PatientInfo
	12, // 14: user.UserService.ListDepartments:input_type -> common.Empty
	11, // 15: user.UserService.GetEmployee:input_type -> common.IdRequest
	6,  // 16: user.UserService.ListEmployees:input_type -> user.EmployeeListRequest
	0,  // 17: user.UserService.GetPatient:output_type -> user.PatientInfo
	2,  // 18: user.UserService.ListPatients:output_type -> user.PatientListResponse
	0,  // 19: user.UserService.CreatePatient:output_type -> user.PatientInfo
	0,  // 20: user.UserService.UpdatePatient:output_type -> user.PatientInfo
	5,  // 21: user.UserService.ListDepartments:output_type -> user.DepartmentListResponse
	4,  // 22: user.UserService.GetEmployee:output_type -> user.EmployeeInfo
	7,  // 23: user.UserService.ListEmployees:output_type -> user.EmployeeListResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
