// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: user/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "his-go/api/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetPatient_FullMethodName      = "/user.UserService/GetPatient"
	UserService_ListPatients_FullMethodName    = "/user.UserService/ListPatients"
	UserService_CreatePatient_FullMethodName   = "/user.UserService/CreatePatient"
	UserService_UpdatePatient_FullMethodName   = "/user.UserService/UpdatePatient"
	UserService_ListDepartments_FullMethodName = "/user.UserService/ListDepartments"
	UserService_GetEmployee_FullMethodName     = "/user.UserService/GetEmployee"
	UserService_ListEmployees_FullMethodName   = "/user.UserService/ListEmployees"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 用户管理服务
type UserServiceClient interface {
	GetPatient(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*PatientInfo, error)
	ListPatients(ctx context.Context, in *PatientListRequest, opts ...grpc.CallOption) (*PatientListResponse, error)
	CreatePatient(ctx context.Context, in *PatientInfo, opts ...grpc.CallOption) (*PatientInfo, error)
	UpdatePatient(ctx context.Context, in *PatientInfo, opts ...grpc.CallOption) (*PatientInfo, error)
	ListDepartments(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*DepartmentListResponse, error)
	GetEmployee(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*EmployeeInfo, error)
	ListEmployees(ctx context.Context, in *EmployeeListRequest, opts ...grpc.CallOption) (*EmployeeListResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetPatient(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*PatientInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatientInfo)
	err := c.cc.Invoke(ctx, UserService_GetPatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListPatients(ctx context.Context, in *PatientListRequest, opts ...grpc.CallOption) (*PatientListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatientListResponse)
	err := c.cc.Invoke(ctx, UserService_ListPatients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreatePatient(ctx context.Context, in *PatientInfo, opts ...grpc.CallOption) (*PatientInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatientInfo)
	err := c.cc.Invoke(ctx, UserService_CreatePatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePatient(ctx context.Context, in *PatientInfo, opts ...grpc.CallOption) (*PatientInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatientInfo)
	err := c.cc.Invoke(ctx, UserService_UpdatePatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListDepartments(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*DepartmentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentListResponse)
	err := c.cc.Invoke(ctx, UserService_ListDepartments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetEmployee(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*EmployeeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmployeeInfo)
	err := c.cc.Invoke(ctx, UserService_GetEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListEmployees(ctx context.Context, in *EmployeeListRequest, opts ...grpc.CallOption) (*EmployeeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmployeeListResponse)
	err := c.cc.Invoke(ctx, UserService_ListEmployees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// 用户管理服务
type UserServiceServer interface {
	GetPatient(context.Context, *common.IdRequest) (*PatientInfo, error)
	ListPatients(context.Context, *PatientListRequest) (*PatientListResponse, error)
	CreatePatient(context.Context, *PatientInfo) (*PatientInfo, error)
	UpdatePatient(context.Context, *PatientInfo) (*PatientInfo, error)
	ListDepartments(context.Context, *common.Empty) (*DepartmentListResponse, error)
	GetEmployee(context.Context, *common.IdRequest) (*EmployeeInfo, error)
	ListEmployees(context.Context, *EmployeeListRequest) (*EmployeeListResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetPatient(context.Context, *common.IdRequest) (*PatientInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPatient not implemented")
}
func (UnimplementedUserServiceServer) ListPatients(context.Context, *PatientListRequest) (*PatientListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPatients not implemented")
}
func (UnimplementedUserServiceServer) CreatePatient(context.Context, *PatientInfo) (*PatientInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePatient not implemented")
}
func (UnimplementedUserServiceServer) UpdatePatient(context.Context, *PatientInfo) (*PatientInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePatient not implemented")
}
func (UnimplementedUserServiceServer) ListDepartments(context.Context, *common.Empty) (*DepartmentListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDepartments not implemented")
}
func (UnimplementedUserServiceServer) GetEmployee(context.Context, *common.IdRequest) (*EmployeeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmployee not implemented")
}
func (UnimplementedUserServiceServer) ListEmployees(context.Context, *EmployeeListRequest) (*EmployeeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEmployees not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetPatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetPatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPatient(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListPatients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListPatients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListPatients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListPatients(ctx, req.(*PatientListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreatePatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreatePatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreatePatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreatePatient(ctx, req.(*PatientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdatePatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePatient(ctx, req.(*PatientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListDepartments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListDepartments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListDepartments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListDepartments(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetEmployee(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListEmployees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListEmployees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListEmployees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListEmployees(ctx, req.(*EmployeeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPatient",
			Handler:    _UserService_GetPatient_Handler,
		},
		{
			MethodName: "ListPatients",
			Handler:    _UserService_ListPatients_Handler,
		},
		{
			MethodName: "CreatePatient",
			Handler:    _UserService_CreatePatient_Handler,
		},
		{
			MethodName: "UpdatePatient",
			Handler:    _UserService_UpdatePatient_Handler,
		},
		{
			MethodName: "ListDepartments",
			Handler:    _UserService_ListDepartments_Handler,
		},
		{
			MethodName: "GetEmployee",
			Handler:    _UserService_GetEmployee_Handler,
		},
		{
			MethodName: "ListEmployees",
			Handler:    _UserService_ListEmployees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}
