// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: prescription/prescription.proto

package prescription

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 处方信息
type PrescriptionInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId        string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PatientName      string                 `protobuf:"bytes,3,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	DoctorId         string                 `protobuf:"bytes,4,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DiagnosisId      string                 `protobuf:"bytes,5,opt,name=diagnosis_id,json=diagnosisId,proto3" json:"diagnosis_id,omitempty"`
	PrescriptionType int32                  `protobuf:"varint,6,opt,name=prescription_type,json=prescriptionType,proto3" json:"prescription_type,omitempty"` // 1-西药 2-中成药 3-中草药
	Status           int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                             // 0-草稿 1-待审核 2-已审核 3-已收费 4-已发药
	Details          []*PrescriptionDetail  `protobuf:"bytes,8,rep,name=details,proto3" json:"details,omitempty"`
	Note             string                 `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrescriptionInfo) Reset() {
	*x = PrescriptionInfo{}
	mi := &file_prescription_prescription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescriptionInfo) ProtoMessage() {}

func (x *PrescriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_prescription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescriptionInfo.ProtoReflect.Descriptor instead.
func (*PrescriptionInfo) Descriptor() ([]byte, []int) {
	return file_prescription_prescription_proto_rawDescGZIP(), []int{0}
}

func (x *PrescriptionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrescriptionInfo) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *PrescriptionInfo) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *PrescriptionInfo) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *PrescriptionInfo) GetDiagnosisId() string {
	if x != nil {
		return x.DiagnosisId
	}
	return ""
}

func (x *PrescriptionInfo) GetPrescriptionType() int32 {
	if x != nil {
		return x.PrescriptionType
	}
	return 0
}

func (x *PrescriptionInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PrescriptionInfo) GetDetails() []*PrescriptionDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *PrescriptionInfo) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *PrescriptionInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 处方明细
type PrescriptionDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PrescriptionId string                 `protobuf:"bytes,2,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	DrugId         string                 `protobuf:"bytes,3,opt,name=drug_id,json=drugId,proto3" json:"drug_id,omitempty"`
	DrugName       string                 `protobuf:"bytes,4,opt,name=drug_name,json=drugName,proto3" json:"drug_name,omitempty"`
	Specification  string                 `protobuf:"bytes,5,opt,name=specification,proto3" json:"specification,omitempty"`
	Dosage         float64                `protobuf:"fixed64,6,opt,name=dosage,proto3" json:"dosage,omitempty"`
	Usage          string                 `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
	Frequency      string                 `protobuf:"bytes,8,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Days           int32                  `protobuf:"varint,9,opt,name=days,proto3" json:"days,omitempty"`
	Quantity       int32                  `protobuf:"varint,10,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice      float64                `protobuf:"fixed64,11,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Note           string                 `protobuf:"bytes,12,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrescriptionDetail) Reset() {
	*x = PrescriptionDetail{}
	mi := &file_prescription_prescription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescriptionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescriptionDetail) ProtoMessage() {}

func (x *PrescriptionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_prescription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescriptionDetail.ProtoReflect.Descriptor instead.
func (*PrescriptionDetail) Descriptor() ([]byte, []int) {
	return file_prescription_prescription_proto_rawDescGZIP(), []int{1}
}

func (x *PrescriptionDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrescriptionDetail) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

func (x *PrescriptionDetail) GetDrugId() string {
	if x != nil {
		return x.DrugId
	}
	return ""
}

func (x *PrescriptionDetail) GetDrugName() string {
	if x != nil {
		return x.DrugName
	}
	return ""
}

func (x *PrescriptionDetail) GetSpecification() string {
	if x != nil {
		return x.Specification
	}
	return ""
}

func (x *PrescriptionDetail) GetDosage() float64 {
	if x != nil {
		return x.Dosage
	}
	return 0
}

func (x *PrescriptionDetail) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *PrescriptionDetail) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *PrescriptionDetail) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *PrescriptionDetail) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PrescriptionDetail) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *PrescriptionDetail) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// 处方列表请求
type PrescriptionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrescriptionListRequest) Reset() {
	*x = PrescriptionListRequest{}
	mi := &file_prescription_prescription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescriptionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescriptionListRequest) ProtoMessage() {}

func (x *PrescriptionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_prescription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescriptionListRequest.ProtoReflect.Descriptor instead.
func (*PrescriptionListRequest) Descriptor() ([]byte, []int) {
	return file_prescription_prescription_proto_rawDescGZIP(), []int{2}
}

func (x *PrescriptionListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PrescriptionListRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *PrescriptionListRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *PrescriptionListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReviewRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrescriptionId string                 `protobuf:"bytes,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	Approved       bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Comment        string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReviewRequest) Reset() {
	*x = ReviewRequest{}
	mi := &file_prescription_prescription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequest) ProtoMessage() {}

func (x *ReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_prescription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequest) Descriptor() ([]byte, []int) {
	return file_prescription_prescription_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewRequest) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

func (x *ReviewRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type PrescriptionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Prescriptions []*PrescriptionInfo    `protobuf:"bytes,2,rep,name=prescriptions,proto3" json:"prescriptions,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrescriptionListResponse) Reset() {
	*x = PrescriptionListResponse{}
	mi := &file_prescription_prescription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescriptionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescriptionListResponse) ProtoMessage() {}

func (x *PrescriptionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_prescription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescriptionListResponse.ProtoReflect.Descriptor instead.
func (*PrescriptionListResponse) Descriptor() ([]byte, []int) {
	return file_prescription_prescription_proto_rawDescGZIP(), []int{4}
}

func (x *PrescriptionListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PrescriptionListResponse) GetPrescriptions() []*PrescriptionInfo {
	if x != nil {
		return x.Prescriptions
	}
	return nil
}

func (x *PrescriptionListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_prescription_prescription_proto protoreflect.FileDescriptor

const file_prescription_prescription_proto_rawDesc = "" +
	"\n" +
	"\x1fprescription/prescription.proto\x12\fprescription\x1a\x13common/common.proto\"\xd8\x02\n" +
	"\x10PrescriptionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12!\n" +
	"\fpatient_name\x18\x03 \x01(\tR\vpatientName\x12\x1b\n" +
	"\tdoctor_id\x18\x04 \x01(\tR\bdoctorId\x12!\n" +
	"\fdiagnosis_id\x18\x05 \x01(\tR\vdiagnosisId\x12+\n" +
	"\x11prescription_type\x18\x06 \x01(\x05R\x10prescriptionType\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12:\n" +
	"\adetails\x18\b \x03(\v2 .prescription.PrescriptionDetailR\adetails\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\xd8\x02\n" +
	"\x12PrescriptionDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fprescription_id\x18\x02 \x01(\tR\x0eprescriptionId\x12\x17\n" +
	"\adrug_id\x18\x03 \x01(\tR\x06drugId\x12\x1b\n" +
	"\tdrug_name\x18\x04 \x01(\tR\bdrugName\x12$\n" +
	"\rspecification\x18\x05 \x01(\tR\rspecification\x12\x16\n" +
	"\x06dosage\x18\x06 \x01(\x01R\x06dosage\x12\x14\n" +
	"\x05usage\x18\a \x01(\tR\x05usage\x12\x1c\n" +
	"\tfrequency\x18\b \x01(\tR\tfrequency\x12\x12\n" +
	"\x04days\x18\t \x01(\x05R\x04days\x12\x1a\n" +
	"\bquantity\x18\n" +
	" \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\v \x01(\x01R\tunitPrice\x12\x12\n" +
	"\x04note\x18\f \x01(\tR\x04note\"\x96\x01\n" +
	"\x17PrescriptionListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"n\n" +
	"\rReviewRequest\x12'\n" +
	"\x0fprescription_id\x18\x01 \x01(\tR\x0eprescriptionId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"\xb4\x01\n" +
	"\x18PrescriptionListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12D\n" +
	"\rprescriptions\x18\x02 \x03(\v2\x1e.prescription.PrescriptionInfoR\rprescriptions\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page2\xa7\x03\n" +
	"\x13PrescriptionService\x12T\n" +
	"\x12CreatePrescription\x12\x1e.prescription.PrescriptionInfo\x1a\x1e.prescription.PrescriptionInfo\x12D\n" +
	"\x0fGetPrescription\x12\x11.common.IdRequest\x1a\x1e.prescription.PrescriptionInfo\x12b\n" +
	"\x11ListPrescriptions\x12%.prescription.PrescriptionListRequest\x1a&.prescription.PrescriptionListResponse\x12Q\n" +
	"\x12ReviewPrescription\x12\x1b.prescription.ReviewRequest\x1a\x1e.prescription.PrescriptionInfo\x12=\n" +
	"\x12CancelPrescription\x12\x11.common.IdRequest\x1a\x14.common.BaseResponseB\x1fZ\x1dhis-go/api/proto/prescriptionb\x06proto3"

var (
	file_prescription_prescription_proto_rawDescOnce sync.Once
	file_prescription_prescription_proto_rawDescData []byte
)

func file_prescription_prescription_proto_rawDescGZIP() []byte {
	file_prescription_prescription_proto_rawDescOnce.Do(func() {
		file_prescription_prescription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prescription_prescription_proto_rawDesc), len(file_prescription_prescription_proto_rawDesc)))
	})
	return file_prescription_prescription_proto_rawDescData
}

var file_prescription_prescription_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_prescription_prescription_proto_goTypes = []any{
	(*PrescriptionInfo)(nil),         // 0: prescription.PrescriptionInfo
	(*PrescriptionDetail)(nil),       // 1: prescription.PrescriptionDetail
	(*PrescriptionListRequest)(nil),  // 2: prescription.PrescriptionListRequest
	(*ReviewRequest)(nil),            // 3: prescription.ReviewRequest
	(*PrescriptionListResponse)(nil), // 4: prescription.PrescriptionListResponse
	(*common.PageRequest)(nil),       // 5: common.PageRequest
	(*common.BaseResponse)(nil),      // 6: common.BaseResponse
	(*common.PageResponse)(nil),      // 7: common.PageResponse
	(*common.IdRequest)(nil),         // 8: common.IdRequest
}
var file_prescription_prescription_proto_depIdxs = []int32{
	1,  // 0: prescription.PrescriptionInfo.details:type_name -> prescription.PrescriptionDetail
	5,  // 1: prescription.PrescriptionListRequest.page:type_name -> common.PageRequest
	6,  // 2: prescription.PrescriptionListResponse.base:type_name -> common.BaseResponse
	0,  // 3: prescription.PrescriptionListResponse.prescriptions:type_name -> prescription.PrescriptionInfo
	7,  // 4: prescription.PrescriptionListResponse.page:type_name -> common.PageResponse
	0,  // 5: prescription.PrescriptionService.CreatePrescription:input_type -> prescription.PrescriptionInfo
	8,  // 6: prescription.PrescriptionService.GetPrescription:input_type -> common.IdRequest
	2,  // 7: prescription.PrescriptionService.ListPrescriptions:input_type -> prescription.PrescriptionListRequest
	3,  // 8: prescription.PrescriptionService.ReviewPrescription:input_type -> prescription.ReviewRequest
	8,  // 9: prescription.PrescriptionService.CancelPrescription:input_type -> common.IdRequest
	0,  // 10: prescription.PrescriptionService.CreatePrescription:output_type -> prescription.PrescriptionInfo
	0,  // 11: prescription.PrescriptionService.GetPrescription:output_type -> prescription.PrescriptionInfo
	4,  // 12: prescription.PrescriptionService.ListPrescriptions:output_type -> prescription.PrescriptionListResponse
	0,  // 13: prescription.PrescriptionService.ReviewPrescription:output_type -> prescription.PrescriptionInfo
	6,  // 14: prescription.PrescriptionService.CancelPrescription:output_type -> common.BaseResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_prescription_prescription_proto_init() }
func file_prescription_prescription_proto_init() {
	if File_prescription_prescription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prescription_prescription_proto_rawDesc), len(file_prescription_prescription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prescription_prescription_proto_goTypes,
		DependencyIndexes: file_prescription_prescription_proto_depIdxs,
		MessageInfos:      file_prescription_prescription_proto_msgTypes,
	}.Build()
	File_prescription_prescription_proto = out.File
	file_prescription_prescription_proto_goTypes = nil
	file_prescription_prescription_proto_depIdxs = nil
}
