// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: prescription/prescription.proto

package prescription

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "his-go/api/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrescriptionService_CreatePrescription_FullMethodName = "/prescription.PrescriptionService/CreatePrescription"
	PrescriptionService_GetPrescription_FullMethodName    = "/prescription.PrescriptionService/GetPrescription"
	PrescriptionService_ListPrescriptions_FullMethodName  = "/prescription.PrescriptionService/ListPrescriptions"
	PrescriptionService_ReviewPrescription_FullMethodName = "/prescription.PrescriptionService/ReviewPrescription"
	PrescriptionService_CancelPrescription_FullMethodName = "/prescription.PrescriptionService/CancelPrescription"
)

// PrescriptionServiceClient is the client API for PrescriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 处方服务
type PrescriptionServiceClient interface {
	CreatePrescription(ctx context.Context, in *PrescriptionInfo, opts ...grpc.CallOption) (*PrescriptionInfo, error)
	GetPrescription(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*PrescriptionInfo, error)
	ListPrescriptions(ctx context.Context, in *PrescriptionListRequest, opts ...grpc.CallOption) (*PrescriptionListResponse, error)
	ReviewPrescription(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*PrescriptionInfo, error)
	CancelPrescription(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.BaseResponse, error)
}

type prescriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrescriptionServiceClient(cc grpc.ClientConnInterface) PrescriptionServiceClient {
	return &prescriptionServiceClient{cc}
}

func (c *prescriptionServiceClient) CreatePrescription(ctx context.Context, in *PrescriptionInfo, opts ...grpc.CallOption) (*PrescriptionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrescriptionInfo)
	err := c.cc.Invoke(ctx, PrescriptionService_CreatePrescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prescriptionServiceClient) GetPrescription(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*PrescriptionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrescriptionInfo)
	err := c.cc.Invoke(ctx, PrescriptionService_GetPrescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prescriptionServiceClient) ListPrescriptions(ctx context.Context, in *PrescriptionListRequest, opts ...grpc.CallOption) (*PrescriptionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrescriptionListResponse)
	err := c.cc.Invoke(ctx, PrescriptionService_ListPrescriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prescriptionServiceClient) ReviewPrescription(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*PrescriptionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrescriptionInfo)
	err := c.cc.Invoke(ctx, PrescriptionService_ReviewPrescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prescriptionServiceClient) CancelPrescription(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, PrescriptionService_CancelPrescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrescriptionServiceServer is the server API for PrescriptionService service.
// All implementations must embed UnimplementedPrescriptionServiceServer
// for forward compatibility.
//
// 处方服务
type PrescriptionServiceServer interface {
	CreatePrescription(context.Context, *PrescriptionInfo) (*PrescriptionInfo, error)
	GetPrescription(context.Context, *common.IdRequest) (*PrescriptionInfo, error)
	ListPrescriptions(context.Context, *PrescriptionListRequest) (*PrescriptionListResponse, error)
	ReviewPrescription(context.Context, *ReviewRequest) (*PrescriptionInfo, error)
	CancelPrescription(context.Context, *common.IdRequest) (*common.BaseResponse, error)
	mustEmbedUnimplementedPrescriptionServiceServer()
}

// UnimplementedPrescriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrescriptionServiceServer struct{}

func (UnimplementedPrescriptionServiceServer) CreatePrescription(context.Context, *PrescriptionInfo) (*PrescriptionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePrescription not implemented")
}
func (UnimplementedPrescriptionServiceServer) GetPrescription(context.Context, *common.IdRequest) (*PrescriptionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrescription not implemented")
}
func (UnimplementedPrescriptionServiceServer) ListPrescriptions(context.Context, *PrescriptionListRequest) (*PrescriptionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPrescriptions not implemented")
}
func (UnimplementedPrescriptionServiceServer) ReviewPrescription(context.Context, *ReviewRequest) (*PrescriptionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewPrescription not implemented")
}
func (UnimplementedPrescriptionServiceServer) CancelPrescription(context.Context, *common.IdRequest) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPrescription not implemented")
}
func (UnimplementedPrescriptionServiceServer) mustEmbedUnimplementedPrescriptionServiceServer() {}
func (UnimplementedPrescriptionServiceServer) testEmbeddedByValue()                             {}

// UnsafePrescriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrescriptionServiceServer will
// result in compilation errors.
type UnsafePrescriptionServiceServer interface {
	mustEmbedUnimplementedPrescriptionServiceServer()
}

func RegisterPrescriptionServiceServer(s grpc.ServiceRegistrar, srv PrescriptionServiceServer) {
	// If the following call panics, it indicates UnimplementedPrescriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrescriptionService_ServiceDesc, srv)
}

func _PrescriptionService_CreatePrescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrescriptionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrescriptionServiceServer).CreatePrescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrescriptionService_CreatePrescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrescriptionServiceServer).CreatePrescription(ctx, req.(*PrescriptionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrescriptionService_GetPrescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrescriptionServiceServer).GetPrescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrescriptionService_GetPrescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrescriptionServiceServer).GetPrescription(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrescriptionService_ListPrescriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrescriptionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrescriptionServiceServer).ListPrescriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrescriptionService_ListPrescriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrescriptionServiceServer).ListPrescriptions(ctx, req.(*PrescriptionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrescriptionService_ReviewPrescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrescriptionServiceServer).ReviewPrescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrescriptionService_ReviewPrescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrescriptionServiceServer).ReviewPrescription(ctx, req.(*ReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrescriptionService_CancelPrescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrescriptionServiceServer).CancelPrescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrescriptionService_CancelPrescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrescriptionServiceServer).CancelPrescription(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrescriptionService_ServiceDesc is the grpc.ServiceDesc for PrescriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrescriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prescription.PrescriptionService",
	HandlerType: (*PrescriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePrescription",
			Handler:    _PrescriptionService_CreatePrescription_Handler,
		},
		{
			MethodName: "GetPrescription",
			Handler:    _PrescriptionService_GetPrescription_Handler,
		},
		{
			MethodName: "ListPrescriptions",
			Handler:    _PrescriptionService_ListPrescriptions_Handler,
		},
		{
			MethodName: "ReviewPrescription",
			Handler:    _PrescriptionService_ReviewPrescription_Handler,
		},
		{
			MethodName: "CancelPrescription",
			Handler:    _PrescriptionService_CancelPrescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prescription/prescription.proto",
}
