// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: registration/registration.proto

package registration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 号源信息
type ScheduleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeptId        string                 `protobuf:"bytes,2,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	DeptName      string                 `protobuf:"bytes,3,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	DoctorId      string                 `protobuf:"bytes,4,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DoctorName    string                 `protobuf:"bytes,5,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	Date          string                 `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	TimeSlot      string                 `protobuf:"bytes,7,opt,name=time_slot,json=timeSlot,proto3" json:"time_slot,omitempty"`
	TotalCount    int32                  `protobuf:"varint,8,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	RemainCount   int32                  `protobuf:"varint,9,opt,name=remain_count,json=remainCount,proto3" json:"remain_count,omitempty"`
	Fee           float64                `protobuf:"fixed64,10,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleInfo) Reset() {
	*x = ScheduleInfo{}
	mi := &file_registration_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleInfo) ProtoMessage() {}

func (x *ScheduleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleInfo.ProtoReflect.Descriptor instead.
func (*ScheduleInfo) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleInfo) GetDeptId() string {
	if x != nil {
		return x.DeptId
	}
	return ""
}

func (x *ScheduleInfo) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *ScheduleInfo) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *ScheduleInfo) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *ScheduleInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ScheduleInfo) GetTimeSlot() string {
	if x != nil {
		return x.TimeSlot
	}
	return ""
}

func (x *ScheduleInfo) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ScheduleInfo) GetRemainCount() int32 {
	if x != nil {
		return x.RemainCount
	}
	return 0
}

func (x *ScheduleInfo) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

// 挂号记录
type RegistrationInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId        string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PatientName      string                 `protobuf:"bytes,3,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	ScheduleId       string                 `protobuf:"bytes,4,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	RegistrationDate string                 `protobuf:"bytes,5,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	QueueNumber      int32                  `protobuf:"varint,6,opt,name=queue_number,json=queueNumber,proto3" json:"queue_number,omitempty"`
	Status           int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"` // 0-已预约 1-已签到 2-已就诊 3-已取消
	CreatedAt        string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegistrationInfo) Reset() {
	*x = RegistrationInfo{}
	mi := &file_registration_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationInfo) ProtoMessage() {}

func (x *RegistrationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationInfo.ProtoReflect.Descriptor instead.
func (*RegistrationInfo) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegistrationInfo) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *RegistrationInfo) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *RegistrationInfo) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *RegistrationInfo) GetRegistrationDate() string {
	if x != nil {
		return x.RegistrationDate
	}
	return ""
}

func (x *RegistrationInfo) GetQueueNumber() int32 {
	if x != nil {
		return x.QueueNumber
	}
	return 0
}

func (x *RegistrationInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RegistrationInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 号源查询请求
type ScheduleQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeptId        string                 `protobuf:"bytes,1,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleQueryRequest) Reset() {
	*x = ScheduleQueryRequest{}
	mi := &file_registration_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleQueryRequest) ProtoMessage() {}

func (x *ScheduleQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleQueryRequest.ProtoReflect.Descriptor instead.
func (*ScheduleQueryRequest) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleQueryRequest) GetDeptId() string {
	if x != nil {
		return x.DeptId
	}
	return ""
}

func (x *ScheduleQueryRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// 挂号请求
type RegistrationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PatientId        string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ScheduleId       string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	PatientName      string                 `protobuf:"bytes,3,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	RegistrationDate string                 `protobuf:"bytes,4,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_registration_registration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *RegistrationRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *RegistrationRequest) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *RegistrationRequest) GetRegistrationDate() string {
	if x != nil {
		return x.RegistrationDate
	}
	return ""
}

// 排队状态
type QueueStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	QueueNumber    int32                  `protobuf:"varint,2,opt,name=queue_number,json=queueNumber,proto3" json:"queue_number,omitempty"`
	CurrentNumber  int32                  `protobuf:"varint,3,opt,name=current_number,json=currentNumber,proto3" json:"current_number,omitempty"`
	WaitCount      int32                  `protobuf:"varint,4,opt,name=wait_count,json=waitCount,proto3" json:"wait_count,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueueStatus) Reset() {
	*x = QueueStatus{}
	mi := &file_registration_registration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatus) ProtoMessage() {}

func (x *QueueStatus) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatus.ProtoReflect.Descriptor instead.
func (*QueueStatus) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{4}
}

func (x *QueueStatus) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *QueueStatus) GetQueueNumber() int32 {
	if x != nil {
		return x.QueueNumber
	}
	return 0
}

func (x *QueueStatus) GetCurrentNumber() int32 {
	if x != nil {
		return x.CurrentNumber
	}
	return 0
}

func (x *QueueStatus) GetWaitCount() int32 {
	if x != nil {
		return x.WaitCount
	}
	return 0
}

func (x *QueueStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ScheduleListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Schedules     []*ScheduleInfo        `protobuf:"bytes,2,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleListResponse) Reset() {
	*x = ScheduleListResponse{}
	mi := &file_registration_registration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleListResponse) ProtoMessage() {}

func (x *ScheduleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registration_registration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleListResponse.ProtoReflect.Descriptor instead.
func (*ScheduleListResponse) Descriptor() ([]byte, []int) {
	return file_registration_registration_proto_rawDescGZIP(), []int{5}
}

func (x *ScheduleListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ScheduleListResponse) GetSchedules() []*ScheduleInfo {
	if x != nil {
		return x.Schedules
	}
	return nil
}

var File_registration_registration_proto protoreflect.FileDescriptor

const file_registration_registration_proto_rawDesc = "" +
	"\n" +
	"\x1fregistration/registration.proto\x12\fregistration\x1a\x13common/common.proto\"\x99\x02\n" +
	"\fScheduleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\adept_id\x18\x02 \x01(\tR\x06deptId\x12\x1b\n" +
	"\tdept_name\x18\x03 \x01(\tR\bdeptName\x12\x1b\n" +
	"\tdoctor_id\x18\x04 \x01(\tR\bdoctorId\x12\x1f\n" +
	"\vdoctor_name\x18\x05 \x01(\tR\n" +
	"doctorName\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\x12\x1b\n" +
	"\ttime_slot\x18\a \x01(\tR\btimeSlot\x12\x1f\n" +
	"\vtotal_count\x18\b \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\fremain_count\x18\t \x01(\x05R\vremainCount\x12\x10\n" +
	"\x03fee\x18\n" +
	" \x01(\x01R\x03fee\"\x8c\x02\n" +
	"\x10RegistrationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12!\n" +
	"\fpatient_name\x18\x03 \x01(\tR\vpatientName\x12\x1f\n" +
	"\vschedule_id\x18\x04 \x01(\tR\n" +
	"scheduleId\x12+\n" +
	"\x11registration_date\x18\x05 \x01(\tR\x10registrationDate\x12!\n" +
	"\fqueue_number\x18\x06 \x01(\x05R\vqueueNumber\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"C\n" +
	"\x14ScheduleQueryRequest\x12\x17\n" +
	"\adept_id\x18\x01 \x01(\tR\x06deptId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"\xa5\x01\n" +
	"\x13RegistrationRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12!\n" +
	"\fpatient_name\x18\x03 \x01(\tR\vpatientName\x12+\n" +
	"\x11registration_date\x18\x04 \x01(\tR\x10registrationDate\"\xb7\x01\n" +
	"\vQueueStatus\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12!\n" +
	"\fqueue_number\x18\x02 \x01(\x05R\vqueueNumber\x12%\n" +
	"\x0ecurrent_number\x18\x03 \x01(\x05R\rcurrentNumber\x12\x1d\n" +
	"\n" +
	"wait_count\x18\x04 \x01(\x05R\twaitCount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"z\n" +
	"\x14ScheduleListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x128\n" +
	"\tschedules\x18\x02 \x03(\v2\x1a.registration.ScheduleInfoR\tschedules2\xae\x03\n" +
	"\x13RegistrationService\x12W\n" +
	"\rListSchedules\x12\".registration.ScheduleQueryRequest\x1a\".registration.ScheduleListResponse\x12M\n" +
	"\bRegister\x12!.registration.RegistrationRequest\x1a\x1e.registration.RegistrationInfo\x12=\n" +
	"\x12CancelRegistration\x12\x11.common.IdRequest\x1a\x14.common.BaseResponse\x121\n" +
	"\x06SignIn\x12\x11.common.IdRequest\x1a\x14.common.BaseResponse\x12>\n" +
	"\x0eGetQueueStatus\x12\x11.common.IdRequest\x1a\x19.registration.QueueStatus\x12=\n" +
	"\bCallNext\x12\x11.common.IdRequest\x1a\x1e.registration.RegistrationInfoB\x1fZ\x1dhis-go/api/proto/registrationb\x06proto3"

var (
	file_registration_registration_proto_rawDescOnce sync.Once
	file_registration_registration_proto_rawDescData []byte
)

func file_registration_registration_proto_rawDescGZIP() []byte {
	file_registration_registration_proto_rawDescOnce.Do(func() {
		file_registration_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registration_registration_proto_rawDesc), len(file_registration_registration_proto_rawDesc)))
	})
	return file_registration_registration_proto_rawDescData
}

var file_registration_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_registration_registration_proto_goTypes = []any{
	(*ScheduleInfo)(nil),         // 0: registration.ScheduleInfo
	(*RegistrationInfo)(nil),     // 1: registration.RegistrationInfo
	(*ScheduleQueryRequest)(nil), // 2: registration.ScheduleQueryRequest
	(*RegistrationRequest)(nil),  // 3: registration.RegistrationRequest
	(*QueueStatus)(nil),          // 4: registration.QueueStatus
	(*ScheduleListResponse)(nil), // 5: registration.ScheduleListResponse
	(*common.BaseResponse)(nil),  // 6: common.BaseResponse
	(*common.IdRequest)(nil),     // 7: common.IdRequest
}
var file_registration_registration_proto_depIdxs = []int32{
	6, // 0: registration.ScheduleListResponse.base:type_name -> common.BaseResponse
	0, // 1: registration.ScheduleListResponse.schedules:type_name -> registration.ScheduleInfo
	2, // 2: registration.RegistrationService.ListSchedules:input_type -> registration.ScheduleQueryRequest
	3, // 3: registration.RegistrationService.Register:input_type -> registration.RegistrationRequest
	7, // 4: registration.RegistrationService.CancelRegistration:input_type -> common.IdRequest
	7, // 5: registration.RegistrationService.SignIn:input_type -> common.IdRequest
	7, // 6: registration.RegistrationService.GetQueueStatus:input_type -> common.IdRequest
	7, // 7: registration.RegistrationService.CallNext:input_type -> common.IdRequest
	5, // 8: registration.RegistrationService.ListSchedules:output_type -> registration.ScheduleListResponse
	1, // 9: registration.RegistrationService.Register:output_type -> registration.RegistrationInfo
	6, // 10: registration.RegistrationService.CancelRegistration:output_type -> common.BaseResponse
	6, // 11: registration.RegistrationService.SignIn:output_type -> common.BaseResponse
	4, // 12: registration.RegistrationService.GetQueueStatus:output_type -> registration.QueueStatus
	1, // 13: registration.RegistrationService.CallNext:output_type -> registration.RegistrationInfo
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_registration_registration_proto_init() }
func file_registration_registration_proto_init() {
	if File_registration_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registration_registration_proto_rawDesc), len(file_registration_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registration_registration_proto_goTypes,
		DependencyIndexes: file_registration_registration_proto_depIdxs,
		MessageInfos:      file_registration_registration_proto_msgTypes,
	}.Build()
	File_registration_registration_proto = out.File
	file_registration_registration_proto_goTypes = nil
	file_registration_registration_proto_depIdxs = nil
}
