// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: registration/registration.proto

package registration

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "his-go/api/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistrationService_ListSchedules_FullMethodName      = "/registration.RegistrationService/ListSchedules"
	RegistrationService_Register_FullMethodName           = "/registration.RegistrationService/Register"
	RegistrationService_CancelRegistration_FullMethodName = "/registration.RegistrationService/CancelRegistration"
	RegistrationService_SignIn_FullMethodName             = "/registration.RegistrationService/SignIn"
	RegistrationService_GetQueueStatus_FullMethodName     = "/registration.RegistrationService/GetQueueStatus"
	RegistrationService_CallNext_FullMethodName           = "/registration.RegistrationService/CallNext"
)

// RegistrationServiceClient is the client API for RegistrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 挂号服务
type RegistrationServiceClient interface {
	ListSchedules(ctx context.Context, in *ScheduleQueryRequest, opts ...grpc.CallOption) (*ScheduleListResponse, error)
	Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationInfo, error)
	CancelRegistration(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.BaseResponse, error)
	SignIn(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.BaseResponse, error)
	GetQueueStatus(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*QueueStatus, error)
	CallNext(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*RegistrationInfo, error)
}

type registrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationServiceClient(cc grpc.ClientConnInterface) RegistrationServiceClient {
	return &registrationServiceClient{cc}
}

func (c *registrationServiceClient) ListSchedules(ctx context.Context, in *ScheduleQueryRequest, opts ...grpc.CallOption) (*ScheduleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleListResponse)
	err := c.cc.Invoke(ctx, RegistrationService_ListSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationInfo)
	err := c.cc.Invoke(ctx, RegistrationService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) CancelRegistration(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, RegistrationService_CancelRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) SignIn(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, RegistrationService_SignIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) GetQueueStatus(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*QueueStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueStatus)
	err := c.cc.Invoke(ctx, RegistrationService_GetQueueStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) CallNext(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*RegistrationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationInfo)
	err := c.cc.Invoke(ctx, RegistrationService_CallNext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServiceServer is the server API for RegistrationService service.
// All implementations must embed UnimplementedRegistrationServiceServer
// for forward compatibility.
//
// 挂号服务
type RegistrationServiceServer interface {
	ListSchedules(context.Context, *ScheduleQueryRequest) (*ScheduleListResponse, error)
	Register(context.Context, *RegistrationRequest) (*RegistrationInfo, error)
	CancelRegistration(context.Context, *common.IdRequest) (*common.BaseResponse, error)
	SignIn(context.Context, *common.IdRequest) (*common.BaseResponse, error)
	GetQueueStatus(context.Context, *common.IdRequest) (*QueueStatus, error)
	CallNext(context.Context, *common.IdRequest) (*RegistrationInfo, error)
	mustEmbedUnimplementedRegistrationServiceServer()
}

// UnimplementedRegistrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistrationServiceServer struct{}

func (UnimplementedRegistrationServiceServer) ListSchedules(context.Context, *ScheduleQueryRequest) (*ScheduleListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchedules not implemented")
}
func (UnimplementedRegistrationServiceServer) Register(context.Context, *RegistrationRequest) (*RegistrationInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegistrationServiceServer) CancelRegistration(context.Context, *common.IdRequest) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRegistration not implemented")
}
func (UnimplementedRegistrationServiceServer) SignIn(context.Context, *common.IdRequest) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedRegistrationServiceServer) GetQueueStatus(context.Context, *common.IdRequest) (*QueueStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueueStatus not implemented")
}
func (UnimplementedRegistrationServiceServer) CallNext(context.Context, *common.IdRequest) (*RegistrationInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CallNext not implemented")
}
func (UnimplementedRegistrationServiceServer) mustEmbedUnimplementedRegistrationServiceServer() {}
func (UnimplementedRegistrationServiceServer) testEmbeddedByValue()                             {}

// UnsafeRegistrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrationServiceServer will
// result in compilation errors.
type UnsafeRegistrationServiceServer interface {
	mustEmbedUnimplementedRegistrationServiceServer()
}

func RegisterRegistrationServiceServer(s grpc.ServiceRegistrar, srv RegistrationServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistrationService_ServiceDesc, srv)
}

func _RegistrationService_ListSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).ListSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_ListSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).ListSchedules(ctx, req.(*ScheduleQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).Register(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_CancelRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).CancelRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_CancelRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).CancelRegistration(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_SignIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).SignIn(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_GetQueueStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).GetQueueStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_GetQueueStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).GetQueueStatus(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_CallNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).CallNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_CallNext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).CallNext(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistrationService_ServiceDesc is the grpc.ServiceDesc for RegistrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registration.RegistrationService",
	HandlerType: (*RegistrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSchedules",
			Handler:    _RegistrationService_ListSchedules_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _RegistrationService_Register_Handler,
		},
		{
			MethodName: "CancelRegistration",
			Handler:    _RegistrationService_CancelRegistration_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _RegistrationService_SignIn_Handler,
		},
		{
			MethodName: "GetQueueStatus",
			Handler:    _RegistrationService_GetQueueStatus_Handler,
		},
		{
			MethodName: "CallNext",
			Handler:    _RegistrationService_CallNext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registration/registration.proto",
}
