// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: examination/examination.proto

package examination

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "his-go/api/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExaminationService_CreateReport_FullMethodName = "/examination.ExaminationService/CreateReport"
	ExaminationService_GetReport_FullMethodName    = "/examination.ExaminationService/GetReport"
	ExaminationService_ReviewReport_FullMethodName = "/examination.ExaminationService/ReviewReport"
	ExaminationService_ListReports_FullMethodName  = "/examination.ExaminationService/ListReports"
)

// ExaminationServiceClient is the client API for ExaminationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 检查服务
type ExaminationServiceClient interface {
	CreateReport(ctx context.Context, in *ExaminationReport, opts ...grpc.CallOption) (*ExaminationReport, error)
	GetReport(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*ExaminationReport, error)
	ReviewReport(ctx context.Context, in *ReviewReportRequest, opts ...grpc.CallOption) (*ExaminationReport, error)
	ListReports(ctx context.Context, in *ReportListRequest, opts ...grpc.CallOption) (*ReportListResponse, error)
}

type examinationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExaminationServiceClient(cc grpc.ClientConnInterface) ExaminationServiceClient {
	return &examinationServiceClient{cc}
}

func (c *examinationServiceClient) CreateReport(ctx context.Context, in *ExaminationReport, opts ...grpc.CallOption) (*ExaminationReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExaminationReport)
	err := c.cc.Invoke(ctx, ExaminationService_CreateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examinationServiceClient) GetReport(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*ExaminationReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExaminationReport)
	err := c.cc.Invoke(ctx, ExaminationService_GetReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examinationServiceClient) ReviewReport(ctx context.Context, in *ReviewReportRequest, opts ...grpc.CallOption) (*ExaminationReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExaminationReport)
	err := c.cc.Invoke(ctx, ExaminationService_ReviewReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examinationServiceClient) ListReports(ctx context.Context, in *ReportListRequest, opts ...grpc.CallOption) (*ReportListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportListResponse)
	err := c.cc.Invoke(ctx, ExaminationService_ListReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExaminationServiceServer is the server API for ExaminationService service.
// All implementations must embed UnimplementedExaminationServiceServer
// for forward compatibility.
//
// 检查服务
type ExaminationServiceServer interface {
	CreateReport(context.Context, *ExaminationReport) (*ExaminationReport, error)
	GetReport(context.Context, *common.IdRequest) (*ExaminationReport, error)
	ReviewReport(context.Context, *ReviewReportRequest) (*ExaminationReport, error)
	ListReports(context.Context, *ReportListRequest) (*ReportListResponse, error)
	mustEmbedUnimplementedExaminationServiceServer()
}

// UnimplementedExaminationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExaminationServiceServer struct{}

func (UnimplementedExaminationServiceServer) CreateReport(context.Context, *ExaminationReport) (*ExaminationReport, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReport not implemented")
}
func (UnimplementedExaminationServiceServer) GetReport(context.Context, *common.IdRequest) (*ExaminationReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReport not implemented")
}
func (UnimplementedExaminationServiceServer) ReviewReport(context.Context, *ReviewReportRequest) (*ExaminationReport, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewReport not implemented")
}
func (UnimplementedExaminationServiceServer) ListReports(context.Context, *ReportListRequest) (*ReportListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReports not implemented")
}
func (UnimplementedExaminationServiceServer) mustEmbedUnimplementedExaminationServiceServer() {}
func (UnimplementedExaminationServiceServer) testEmbeddedByValue()                            {}

// UnsafeExaminationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExaminationServiceServer will
// result in compilation errors.
type UnsafeExaminationServiceServer interface {
	mustEmbedUnimplementedExaminationServiceServer()
}

func RegisterExaminationServiceServer(s grpc.ServiceRegistrar, srv ExaminationServiceServer) {
	// If the following call panics, it indicates UnimplementedExaminationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExaminationService_ServiceDesc, srv)
}

func _ExaminationService_CreateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExaminationReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExaminationServiceServer).CreateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExaminationService_CreateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExaminationServiceServer).CreateReport(ctx, req.(*ExaminationReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExaminationService_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExaminationServiceServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExaminationService_GetReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExaminationServiceServer).GetReport(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExaminationService_ReviewReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExaminationServiceServer).ReviewReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExaminationService_ReviewReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExaminationServiceServer).ReviewReport(ctx, req.(*ReviewReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExaminationService_ListReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExaminationServiceServer).ListReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExaminationService_ListReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExaminationServiceServer).ListReports(ctx, req.(*ReportListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExaminationService_ServiceDesc is the grpc.ServiceDesc for ExaminationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExaminationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "examination.ExaminationService",
	HandlerType: (*ExaminationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReport",
			Handler:    _ExaminationService_CreateReport_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _ExaminationService_GetReport_Handler,
		},
		{
			MethodName: "ReviewReport",
			Handler:    _ExaminationService_ReviewReport_Handler,
		},
		{
			MethodName: "ListReports",
			Handler:    _ExaminationService_ListReports_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examination/examination.proto",
}
