// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: pharmacy/pharmacy.proto

package pharmacy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 药品信息
type DrugInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GenericName   string                 `protobuf:"bytes,3,opt,name=generic_name,json=genericName,proto3" json:"generic_name,omitempty"`
	Specification string                 `protobuf:"bytes,4,opt,name=specification,proto3" json:"specification,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,5,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	BatchNo       string                 `protobuf:"bytes,6,opt,name=batch_no,json=batchNo,proto3" json:"batch_no,omitempty"`
	PurchasePrice float64                `protobuf:"fixed64,7,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	RetailPrice   float64                `protobuf:"fixed64,8,opt,name=retail_price,json=retailPrice,proto3" json:"retail_price,omitempty"`
	Stock         int32                  `protobuf:"varint,9,opt,name=stock,proto3" json:"stock,omitempty"`
	MinStock      int32                  `protobuf:"varint,10,opt,name=min_stock,json=minStock,proto3" json:"min_stock,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,11,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	Status        int32                  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrugInfo) Reset() {
	*x = DrugInfo{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrugInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrugInfo) ProtoMessage() {}

func (x *DrugInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrugInfo.ProtoReflect.Descriptor instead.
func (*DrugInfo) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{0}
}

func (x *DrugInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DrugInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DrugInfo) GetGenericName() string {
	if x != nil {
		return x.GenericName
	}
	return ""
}

func (x *DrugInfo) GetSpecification() string {
	if x != nil {
		return x.Specification
	}
	return ""
}

func (x *DrugInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *DrugInfo) GetBatchNo() string {
	if x != nil {
		return x.BatchNo
	}
	return ""
}

func (x *DrugInfo) GetPurchasePrice() float64 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *DrugInfo) GetRetailPrice() float64 {
	if x != nil {
		return x.RetailPrice
	}
	return 0
}

func (x *DrugInfo) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *DrugInfo) GetMinStock() int32 {
	if x != nil {
		return x.MinStock
	}
	return 0
}

func (x *DrugInfo) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *DrugInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 发药记录
type DispenseRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PrescriptionId string                 `protobuf:"bytes,2,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	PatientId      string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DrugId         string                 `protobuf:"bytes,4,opt,name=drug_id,json=drugId,proto3" json:"drug_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	DispenserId    string                 `protobuf:"bytes,6,opt,name=dispenser_id,json=dispenserId,proto3" json:"dispenser_id,omitempty"`
	CheckerId      string                 `protobuf:"bytes,7,opt,name=checker_id,json=checkerId,proto3" json:"checker_id,omitempty"`
	Status         int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispenseRecord) Reset() {
	*x = DispenseRecord{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispenseRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispenseRecord) ProtoMessage() {}

func (x *DispenseRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispenseRecord.ProtoReflect.Descriptor instead.
func (*DispenseRecord) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{1}
}

func (x *DispenseRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DispenseRecord) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

func (x *DispenseRecord) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *DispenseRecord) GetDrugId() string {
	if x != nil {
		return x.DrugId
	}
	return ""
}

func (x *DispenseRecord) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DispenseRecord) GetDispenserId() string {
	if x != nil {
		return x.DispenserId
	}
	return ""
}

func (x *DispenseRecord) GetCheckerId() string {
	if x != nil {
		return x.CheckerId
	}
	return ""
}

func (x *DispenseRecord) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DispenseRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DrugListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrugListRequest) Reset() {
	*x = DrugListRequest{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrugListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrugListRequest) ProtoMessage() {}

func (x *DrugListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrugListRequest.ProtoReflect.Descriptor instead.
func (*DrugListRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{2}
}

func (x *DrugListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *DrugListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DrugListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DrugListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Drugs         []*DrugInfo            `protobuf:"bytes,2,rep,name=drugs,proto3" json:"drugs,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrugListResponse) Reset() {
	*x = DrugListResponse{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrugListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrugListResponse) ProtoMessage() {}

func (x *DrugListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrugListResponse.ProtoReflect.Descriptor instead.
func (*DrugListResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{3}
}

func (x *DrugListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DrugListResponse) GetDrugs() []*DrugInfo {
	if x != nil {
		return x.Drugs
	}
	return nil
}

func (x *DrugListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type StockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrugId        string                 `protobuf:"bytes,1,opt,name=drug_id,json=drugId,proto3" json:"drug_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockRequest) Reset() {
	*x = StockRequest{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockRequest) ProtoMessage() {}

func (x *StockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockRequest.ProtoReflect.Descriptor instead.
func (*StockRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{4}
}

func (x *StockRequest) GetDrugId() string {
	if x != nil {
		return x.DrugId
	}
	return ""
}

func (x *StockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DispenseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrescriptionId string                 `protobuf:"bytes,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispenseRequest) Reset() {
	*x = DispenseRequest{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispenseRequest) ProtoMessage() {}

func (x *DispenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispenseRequest.ProtoReflect.Descriptor instead.
func (*DispenseRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{5}
}

func (x *DispenseRequest) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

type ExpiredDrugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ExpiredDrugs  []*DrugInfo            `protobuf:"bytes,2,rep,name=expired_drugs,json=expiredDrugs,proto3" json:"expired_drugs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpiredDrugResponse) Reset() {
	*x = ExpiredDrugResponse{}
	mi := &file_pharmacy_pharmacy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpiredDrugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpiredDrugResponse) ProtoMessage() {}

func (x *ExpiredDrugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpiredDrugResponse.ProtoReflect.Descriptor instead.
func (*ExpiredDrugResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{6}
}

func (x *ExpiredDrugResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ExpiredDrugResponse) GetExpiredDrugs() []*DrugInfo {
	if x != nil {
		return x.ExpiredDrugs
	}
	return nil
}

var File_pharmacy_pharmacy_proto protoreflect.FileDescriptor

const file_pharmacy_pharmacy_proto_rawDesc = "" +
	"\n" +
	"\x17pharmacy/pharmacy.proto\x12\bpharmacy\x1a\x13common/common.proto\"\xec\x02\n" +
	"\bDrugInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fgeneric_name\x18\x03 \x01(\tR\vgenericName\x12$\n" +
	"\rspecification\x18\x04 \x01(\tR\rspecification\x12\"\n" +
	"\fmanufacturer\x18\x05 \x01(\tR\fmanufacturer\x12\x19\n" +
	"\bbatch_no\x18\x06 \x01(\tR\abatchNo\x12%\n" +
	"\x0epurchase_price\x18\a \x01(\x01R\rpurchasePrice\x12!\n" +
	"\fretail_price\x18\b \x01(\x01R\vretailPrice\x12\x14\n" +
	"\x05stock\x18\t \x01(\x05R\x05stock\x12\x1b\n" +
	"\tmin_stock\x18\n" +
	" \x01(\x05R\bminStock\x12\x1f\n" +
	"\vexpiry_date\x18\v \x01(\tR\n" +
	"expiryDate\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\"\x96\x02\n" +
	"\x0eDispenseRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fprescription_id\x18\x02 \x01(\tR\x0eprescriptionId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12\x17\n" +
	"\adrug_id\x18\x04 \x01(\tR\x06drugId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12!\n" +
	"\fdispenser_id\x18\x06 \x01(\tR\vdispenserId\x12\x1d\n" +
	"\n" +
	"checker_id\x18\a \x01(\tR\tcheckerId\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"f\n" +
	"\x0fDrugListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\x90\x01\n" +
	"\x10DrugListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12(\n" +
	"\x05drugs\x18\x02 \x03(\v2\x12.pharmacy.DrugInfoR\x05drugs\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page\"W\n" +
	"\fStockRequest\x12\x17\n" +
	"\adrug_id\x18\x01 \x01(\tR\x06drugId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\":\n" +
	"\x0fDispenseRequest\x12'\n" +
	"\x0fprescription_id\x18\x01 \x01(\tR\x0eprescriptionId\"x\n" +
	"\x13ExpiredDrugResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x127\n" +
	"\rexpired_drugs\x18\x02 \x03(\v2\x12.pharmacy.DrugInfoR\fexpiredDrugs2\x82\x03\n" +
	"\x0fPharmacyService\x12B\n" +
	"\tListDrugs\x12\x19.pharmacy.DrugListRequest\x1a\x1a.pharmacy.DrugListResponse\x120\n" +
	"\aGetDrug\x12\x11.common.IdRequest\x1a\x12.pharmacy.DrugInfo\x126\n" +
	"\bAddStock\x12\x16.pharmacy.StockRequest\x1a\x12.pharmacy.DrugInfo\x129\n" +
	"\vReduceStock\x12\x16.pharmacy.StockRequest\x1a\x12.pharmacy.DrugInfo\x12C\n" +
	"\fDispenseDrug\x12\x19.pharmacy.DispenseRequest\x1a\x18.pharmacy.DispenseRecord\x12A\n" +
	"\x11CheckExpiredDrugs\x12\r.common.Empty\x1a\x1d.pharmacy.ExpiredDrugResponseB\x1bZ\x19his-go/api/proto/pharmacyb\x06proto3"

var (
	file_pharmacy_pharmacy_proto_rawDescOnce sync.Once
	file_pharmacy_pharmacy_proto_rawDescData []byte
)

func file_pharmacy_pharmacy_proto_rawDescGZIP() []byte {
	file_pharmacy_pharmacy_proto_rawDescOnce.Do(func() {
		file_pharmacy_pharmacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pharmacy_pharmacy_proto_rawDesc), len(file_pharmacy_pharmacy_proto_rawDesc)))
	})
	return file_pharmacy_pharmacy_proto_rawDescData
}

var file_pharmacy_pharmacy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pharmacy_pharmacy_proto_goTypes = []any{
	(*DrugInfo)(nil),            // 0: pharmacy.DrugInfo
	(*DispenseRecord)(nil),      // 1: pharmacy.DispenseRecord
	(*DrugListRequest)(nil),     // 2: pharmacy.DrugListRequest
	(*DrugListResponse)(nil),    // 3: pharmacy.DrugListResponse
	(*StockRequest)(nil),        // 4: pharmacy.StockRequest
	(*DispenseRequest)(nil),     // 5: pharmacy.DispenseRequest
	(*ExpiredDrugResponse)(nil), // 6: pharmacy.ExpiredDrugResponse
	(*common.PageRequest)(nil),  // 7: common.PageRequest
	(*common.BaseResponse)(nil), // 8: common.BaseResponse
	(*common.PageResponse)(nil), // 9: common.PageResponse
	(*common.IdRequest)(nil),    // 10: common.IdRequest
	(*common.Empty)(nil),        // 11: common.Empty
}
var file_pharmacy_pharmacy_proto_depIdxs = []int32{
	7,  // 0: pharmacy.DrugListRequest.page:type_name -> common.PageRequest
	8,  // 1: pharmacy.DrugListResponse.base:type_name -> common.BaseResponse
	0,  // 2: pharmacy.DrugListResponse.drugs:type_name -> pharmacy.DrugInfo
	9,  // 3: pharmacy.DrugListResponse.page:type_name -> common.PageResponse
	8,  // 4: pharmacy.ExpiredDrugResponse.base:type_name -> common.BaseResponse
	0,  // 5: pharmacy.ExpiredDrugResponse.expired_drugs:type_name -> pharmacy.DrugInfo
	2,  // 6: pharmacy.PharmacyService.ListDrugs:input_type -> pharmacy.DrugListRequest
	10, // 7: pharmacy.PharmacyService.GetDrug:input_type -> common.IdRequest
	4,  // 8: pharmacy.PharmacyService.AddStock:input_type -> pharmacy.StockRequest
	4,  // 9: pharmacy.PharmacyService.ReduceStock:input_type -> pharmacy.StockRequest
	5,  // 10: pharmacy.PharmacyService.DispenseDrug:input_type -> pharmacy.DispenseRequest
	11, // 11: pharmacy.PharmacyService.CheckExpiredDrugs:input_type -> common.Empty
	3,  // 12: pharmacy.PharmacyService.ListDrugs:output_type -> pharmacy.DrugListResponse
	0,  // 13: pharmacy.PharmacyService.GetDrug:output_type -> pharmacy.DrugInfo
	0,  // 14: pharmacy.PharmacyService.AddStock:output_type -> pharmacy.DrugInfo
	0,  // 15: pharmacy.PharmacyService.ReduceStock:output_type -> pharmacy.DrugInfo
	1,  // 16: pharmacy.PharmacyService.DispenseDrug:output_type -> pharmacy.DispenseRecord
	6,  // 17: pharmacy.PharmacyService.CheckExpiredDrugs:output_type -> pharmacy.ExpiredDrugResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pharmacy_pharmacy_proto_init() }
func file_pharmacy_pharmacy_proto_init() {
	if File_pharmacy_pharmacy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pharmacy_pharmacy_proto_rawDesc), len(file_pharmacy_pharmacy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pharmacy_pharmacy_proto_goTypes,
		DependencyIndexes: file_pharmacy_pharmacy_proto_depIdxs,
		MessageInfos:      file_pharmacy_pharmacy_proto_msgTypes,
	}.Build()
	File_pharmacy_pharmacy_proto = out.File
	file_pharmacy_pharmacy_proto_goTypes = nil
	file_pharmacy_pharmacy_proto_depIdxs = nil
}
