// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: pharmacy/pharmacy.proto

package pharmacy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "his-go/api/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PharmacyService_ListDrugs_FullMethodName         = "/pharmacy.PharmacyService/ListDrugs"
	PharmacyService_GetDrug_FullMethodName           = "/pharmacy.PharmacyService/GetDrug"
	PharmacyService_AddStock_FullMethodName          = "/pharmacy.PharmacyService/AddStock"
	PharmacyService_ReduceStock_FullMethodName       = "/pharmacy.PharmacyService/ReduceStock"
	PharmacyService_DispenseDrug_FullMethodName      = "/pharmacy.PharmacyService/DispenseDrug"
	PharmacyService_CheckExpiredDrugs_FullMethodName = "/pharmacy.PharmacyService/CheckExpiredDrugs"
)

// PharmacyServiceClient is the client API for PharmacyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 药房服务
type PharmacyServiceClient interface {
	ListDrugs(ctx context.Context, in *DrugListRequest, opts ...grpc.CallOption) (*DrugListResponse, error)
	GetDrug(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*DrugInfo, error)
	AddStock(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*DrugInfo, error)
	ReduceStock(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*DrugInfo, error)
	DispenseDrug(ctx context.Context, in *DispenseRequest, opts ...grpc.CallOption) (*DispenseRecord, error)
	CheckExpiredDrugs(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ExpiredDrugResponse, error)
}

type pharmacyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPharmacyServiceClient(cc grpc.ClientConnInterface) PharmacyServiceClient {
	return &pharmacyServiceClient{cc}
}

func (c *pharmacyServiceClient) ListDrugs(ctx context.Context, in *DrugListRequest, opts ...grpc.CallOption) (*DrugListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrugListResponse)
	err := c.cc.Invoke(ctx, PharmacyService_ListDrugs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) GetDrug(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*DrugInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrugInfo)
	err := c.cc.Invoke(ctx, PharmacyService_GetDrug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) AddStock(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*DrugInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrugInfo)
	err := c.cc.Invoke(ctx, PharmacyService_AddStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) ReduceStock(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*DrugInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrugInfo)
	err := c.cc.Invoke(ctx, PharmacyService_ReduceStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) DispenseDrug(ctx context.Context, in *DispenseRequest, opts ...grpc.CallOption) (*DispenseRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispenseRecord)
	err := c.cc.Invoke(ctx, PharmacyService_DispenseDrug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) CheckExpiredDrugs(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ExpiredDrugResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpiredDrugResponse)
	err := c.cc.Invoke(ctx, PharmacyService_CheckExpiredDrugs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PharmacyServiceServer is the server API for PharmacyService service.
// All implementations must embed UnimplementedPharmacyServiceServer
// for forward compatibility.
//
// 药房服务
type PharmacyServiceServer interface {
	ListDrugs(context.Context, *DrugListRequest) (*DrugListResponse, error)
	GetDrug(context.Context, *common.IdRequest) (*DrugInfo, error)
	AddStock(context.Context, *StockRequest) (*DrugInfo, error)
	ReduceStock(context.Context, *StockRequest) (*DrugInfo, error)
	DispenseDrug(context.Context, *DispenseRequest) (*DispenseRecord, error)
	CheckExpiredDrugs(context.Context, *common.Empty) (*ExpiredDrugResponse, error)
	mustEmbedUnimplementedPharmacyServiceServer()
}

// UnimplementedPharmacyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPharmacyServiceServer struct{}

func (UnimplementedPharmacyServiceServer) ListDrugs(context.Context, *DrugListRequest) (*DrugListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrugs not implemented")
}
func (UnimplementedPharmacyServiceServer) GetDrug(context.Context, *common.IdRequest) (*DrugInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDrug not implemented")
}
func (UnimplementedPharmacyServiceServer) AddStock(context.Context, *StockRequest) (*DrugInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method AddStock not implemented")
}
func (UnimplementedPharmacyServiceServer) ReduceStock(context.Context, *StockRequest) (*DrugInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method ReduceStock not implemented")
}
func (UnimplementedPharmacyServiceServer) DispenseDrug(context.Context, *DispenseRequest) (*DispenseRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method DispenseDrug not implemented")
}
func (UnimplementedPharmacyServiceServer) CheckExpiredDrugs(context.Context, *common.Empty) (*ExpiredDrugResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckExpiredDrugs not implemented")
}
func (UnimplementedPharmacyServiceServer) mustEmbedUnimplementedPharmacyServiceServer() {}
func (UnimplementedPharmacyServiceServer) testEmbeddedByValue()                         {}

// UnsafePharmacyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PharmacyServiceServer will
// result in compilation errors.
type UnsafePharmacyServiceServer interface {
	mustEmbedUnimplementedPharmacyServiceServer()
}

func RegisterPharmacyServiceServer(s grpc.ServiceRegistrar, srv PharmacyServiceServer) {
	// If the following call panics, it indicates UnimplementedPharmacyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PharmacyService_ServiceDesc, srv)
}

func _PharmacyService_ListDrugs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrugListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).ListDrugs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_ListDrugs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).ListDrugs(ctx, req.(*DrugListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_GetDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).GetDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_GetDrug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).GetDrug(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_AddStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).AddStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_AddStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).AddStock(ctx, req.(*StockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_ReduceStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).ReduceStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_ReduceStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).ReduceStock(ctx, req.(*StockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_DispenseDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).DispenseDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_DispenseDrug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).DispenseDrug(ctx, req.(*DispenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_CheckExpiredDrugs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).CheckExpiredDrugs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_CheckExpiredDrugs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).CheckExpiredDrugs(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PharmacyService_ServiceDesc is the grpc.ServiceDesc for PharmacyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PharmacyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pharmacy.PharmacyService",
	HandlerType: (*PharmacyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDrugs",
			Handler:    _PharmacyService_ListDrugs_Handler,
		},
		{
			MethodName: "GetDrug",
			Handler:    _PharmacyService_GetDrug_Handler,
		},
		{
			MethodName: "AddStock",
			Handler:    _PharmacyService_AddStock_Handler,
		},
		{
			MethodName: "ReduceStock",
			Handler:    _PharmacyService_ReduceStock_Handler,
		},
		{
			MethodName: "DispenseDrug",
			Handler:    _PharmacyService_DispenseDrug_Handler,
		},
		{
			MethodName: "CheckExpiredDrugs",
			Handler:    _PharmacyService_CheckExpiredDrugs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pharmacy/pharmacy.proto",
}
