// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: outpatient/outpatient.proto

package outpatient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 在线问诊
type Consultation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"` // 1-图文 2-视频
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	Messages      []*ConsultationMessage `protobuf:"bytes,7,rep,name=messages,proto3" json:"messages,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consultation) Reset() {
	*x = Consultation{}
	mi := &file_outpatient_outpatient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consultation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consultation) ProtoMessage() {}

func (x *Consultation) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consultation.ProtoReflect.Descriptor instead.
func (*Consultation) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{0}
}

func (x *Consultation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Consultation) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Consultation) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *Consultation) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Consultation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Consultation) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Consultation) GetMessages() []*ConsultationMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Consultation) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Consultation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 问诊消息
type ConsultationMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConsultationId string                 `protobuf:"bytes,2,opt,name=consultation_id,json=consultationId,proto3" json:"consultation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName     string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MsgType        string                 `protobuf:"bytes,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsultationMessage) Reset() {
	*x = ConsultationMessage{}
	mi := &file_outpatient_outpatient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultationMessage) ProtoMessage() {}

func (x *ConsultationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultationMessage.ProtoReflect.Descriptor instead.
func (*ConsultationMessage) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{1}
}

func (x *ConsultationMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsultationMessage) GetConsultationId() string {
	if x != nil {
		return x.ConsultationId
	}
	return ""
}

func (x *ConsultationMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ConsultationMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ConsultationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConsultationMessage) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *ConsultationMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 慢病签约
type ChronicContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DiseaseType   string                 `protobuf:"bytes,4,opt,name=disease_type,json=diseaseType,proto3" json:"disease_type,omitempty"`
	ContractDate  string                 `protobuf:"bytes,5,opt,name=contract_date,json=contractDate,proto3" json:"contract_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChronicContract) Reset() {
	*x = ChronicContract{}
	mi := &file_outpatient_outpatient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChronicContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChronicContract) ProtoMessage() {}

func (x *ChronicContract) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChronicContract.ProtoReflect.Descriptor instead.
func (*ChronicContract) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{2}
}

func (x *ChronicContract) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChronicContract) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ChronicContract) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *ChronicContract) GetDiseaseType() string {
	if x != nil {
		return x.DiseaseType
	}
	return ""
}

func (x *ChronicContract) GetContractDate() string {
	if x != nil {
		return x.ContractDate
	}
	return ""
}

func (x *ChronicContract) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ChronicContract) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 健康数据
type HealthData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // blood_pressure, blood_sugar, weight
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	MeasureTime   string                 `protobuf:"bytes,6,opt,name=measure_time,json=measureTime,proto3" json:"measure_time,omitempty"`
	Abnormal      bool                   `protobuf:"varint,7,opt,name=abnormal,proto3" json:"abnormal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthData) Reset() {
	*x = HealthData{}
	mi := &file_outpatient_outpatient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthData) ProtoMessage() {}

func (x *HealthData) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthData.ProtoReflect.Descriptor instead.
func (*HealthData) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{3}
}

func (x *HealthData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HealthData) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *HealthData) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *HealthData) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *HealthData) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *HealthData) GetMeasureTime() string {
	if x != nil {
		return x.MeasureTime
	}
	return ""
}

func (x *HealthData) GetAbnormal() bool {
	if x != nil {
		return x.Abnormal
	}
	return false
}

type ConsultationListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultationListRequest) Reset() {
	*x = ConsultationListRequest{}
	mi := &file_outpatient_outpatient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultationListRequest) ProtoMessage() {}

func (x *ConsultationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultationListRequest.ProtoReflect.Descriptor instead.
func (*ConsultationListRequest) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{4}
}

func (x *ConsultationListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ConsultationListRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ConsultationListRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *ConsultationListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ConsultationListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Consultations []*Consultation        `protobuf:"bytes,2,rep,name=consultations,proto3" json:"consultations,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultationListResponse) Reset() {
	*x = ConsultationListResponse{}
	mi := &file_outpatient_outpatient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultationListResponse) ProtoMessage() {}

func (x *ConsultationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outpatient_outpatient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultationListResponse.ProtoReflect.Descriptor instead.
func (*ConsultationListResponse) Descriptor() ([]byte, []int) {
	return file_outpatient_outpatient_proto_rawDescGZIP(), []int{5}
}

func (x *ConsultationListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ConsultationListResponse) GetConsultations() []*Consultation {
	if x != nil {
		return x.Consultations
	}
	return nil
}

func (x *ConsultationListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_outpatient_outpatient_proto protoreflect.FileDescriptor

const file_outpatient_outpatient_proto_rawDesc = "" +
	"\n" +
	"\x1boutpatient/outpatient.proto\x12\n" +
	"outpatient\x1a\x13common/common.proto\"\x9c\x02\n" +
	"\fConsultation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\x12;\n" +
	"\bmessages\x18\a \x03(\v2\x1f.outpatient.ConsultationMessageR\bmessages\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"\xe0\x01\n" +
	"\x13ConsultationMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconsultation_id\x18\x02 \x01(\tR\x0econsultationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x19\n" +
	"\bmsg_type\x18\x06 \x01(\tR\amsgType\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\xd8\x01\n" +
	"\x0fChronicContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12!\n" +
	"\fdisease_type\x18\x04 \x01(\tR\vdiseaseType\x12#\n" +
	"\rcontract_date\x18\x05 \x01(\tR\fcontractDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"\xc1\x01\n" +
	"\n" +
	"HealthData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12!\n" +
	"\fmeasure_time\x18\x06 \x01(\tR\vmeasureTime\x12\x1a\n" +
	"\babnormal\x18\a \x01(\bR\babnormal\"\x96\x01\n" +
	"\x17ConsultationListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\xae\x01\n" +
	"\x18ConsultationListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12>\n" +
	"\rconsultations\x18\x02 \x03(\v2\x18.outpatient.ConsultationR\rconsultations\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page2\xe5\x03\n" +
	"\x11OutpatientService\x12H\n" +
	"\x12CreateConsultation\x12\x18.outpatient.Consultation\x1a\x18.outpatient.Consultation\x12>\n" +
	"\x0fGetConsultation\x12\x11.common.IdRequest\x1a\x18.outpatient.Consultation\x12O\n" +
	"\vSendMessage\x12\x1f.outpatient.ConsultationMessage\x1a\x1f.outpatient.ConsultationMessage\x12Q\n" +
	"\x15CreateChronicContract\x12\x1b.outpatient.ChronicContract\x1a\x1b.outpatient.ChronicContract\x12B\n" +
	"\x10ReportHealthData\x12\x16.outpatient.HealthData\x1a\x16.outpatient.HealthData\x12^\n" +
	"\x11ListConsultations\x12#.outpatient.ConsultationListRequest\x1a$.outpatient.ConsultationListResponseB\x1dZ\x1bhis-go/api/proto/outpatientb\x06proto3"

var (
	file_outpatient_outpatient_proto_rawDescOnce sync.Once
	file_outpatient_outpatient_proto_rawDescData []byte
)

func file_outpatient_outpatient_proto_rawDescGZIP() []byte {
	file_outpatient_outpatient_proto_rawDescOnce.Do(func() {
		file_outpatient_outpatient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outpatient_outpatient_proto_rawDesc), len(file_outpatient_outpatient_proto_rawDesc)))
	})
	return file_outpatient_outpatient_proto_rawDescData
}

var file_outpatient_outpatient_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_outpatient_outpatient_proto_goTypes = []any{
	(*Consultation)(nil),             // 0: outpatient.Consultation
	(*ConsultationMessage)(nil),      // 1: outpatient.ConsultationMessage
	(*ChronicContract)(nil),          // 2: outpatient.ChronicContract
	(*HealthData)(nil),               // 3: outpatient.HealthData
	(*ConsultationListRequest)(nil),  // 4: outpatient.ConsultationListRequest
	(*ConsultationListResponse)(nil), // 5: outpatient.ConsultationListResponse
	(*common.PageRequest)(nil),       // 6: common.PageRequest
	(*common.BaseResponse)(nil),      // 7: common.BaseResponse
	(*common.PageResponse)(nil),      // 8: common.PageResponse
	(*common.IdRequest)(nil),         // 9: common.IdRequest
}
var file_outpatient_outpatient_proto_depIdxs = []int32{
	1,  // 0: outpatient.Consultation.messages:type_name -> outpatient.ConsultationMessage
	6,  // 1: outpatient.ConsultationListRequest.page:type_name -> common.PageRequest
	7,  // 2: outpatient.ConsultationListResponse.base:type_name -> common.BaseResponse
	0,  // 3: outpatient.ConsultationListResponse.consultations:type_name -> outpatient.Consultation
	8,  // 4: outpatient.ConsultationListResponse.page:type_name -> common.PageResponse
	0,  // 5: outpatient.OutpatientService.CreateConsultation:input_type -> outpatient.Consultation
	9,  // 6: outpatient.OutpatientService.GetConsultation:input_type -> common.IdRequest
	1,  // 7: outpatient.OutpatientService.SendMessage:input_type -> outpatient.ConsultationMessage
	2,  // 8: outpatient.OutpatientService.CreateChronicContract:input_type -> outpatient.ChronicContract
	3,  // 9: outpatient.OutpatientService.ReportHealthData:input_type -> outpatient.HealthData
	4,  // 10: outpatient.OutpatientService.ListConsultations:input_type -> outpatient.ConsultationListRequest
	0,  // 11: outpatient.OutpatientService.CreateConsultation:output_type -> outpatient.Consultation
	0,  // 12: outpatient.OutpatientService.GetConsultation:output_type -> outpatient.Consultation
	1,  // 13: outpatient.OutpatientService.SendMessage:output_type -> outpatient.ConsultationMessage
	2,  // 14: outpatient.OutpatientService.CreateChronicContract:output_type -> outpatient.ChronicContract
	3,  // 15: outpatient.OutpatientService.ReportHealthData:output_type -> outpatient.HealthData
	5,  // 16: outpatient.OutpatientService.ListConsultations:output_type -> outpatient.ConsultationListResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_outpatient_outpatient_proto_init() }
func file_outpatient_outpatient_proto_init() {
	if File_outpatient_outpatient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outpatient_outpatient_proto_rawDesc), len(file_outpatient_outpatient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outpatient_outpatient_proto_goTypes,
		DependencyIndexes: file_outpatient_outpatient_proto_depIdxs,
		MessageInfos:      file_outpatient_outpatient_proto_msgTypes,
	}.Build()
	File_outpatient_outpatient_proto = out.File
	file_outpatient_outpatient_proto_goTypes = nil
	file_outpatient_outpatient_proto_depIdxs = nil
}
