// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: clinic/clinic.proto

package clinic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 接诊记录
type ClinicRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegistrationId string                 `protobuf:"bytes,2,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	PatientId      string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PatientName    string                 `protobuf:"bytes,4,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	DoctorId       string                 `protobuf:"bytes,5,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	ChiefComplaint string                 `protobuf:"bytes,6,opt,name=chief_complaint,json=chiefComplaint,proto3" json:"chief_complaint,omitempty"`
	PresentIllness string                 `protobuf:"bytes,7,opt,name=present_illness,json=presentIllness,proto3" json:"present_illness,omitempty"`
	Diagnosis      string                 `protobuf:"bytes,8,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	IcdCode        string                 `protobuf:"bytes,9,opt,name=icd_code,json=icdCode,proto3" json:"icd_code,omitempty"`
	Advice         string                 `protobuf:"bytes,10,opt,name=advice,proto3" json:"advice,omitempty"`
	Status         int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	VisitTime      string                 `protobuf:"bytes,12,opt,name=visit_time,json=visitTime,proto3" json:"visit_time,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClinicRecord) Reset() {
	*x = ClinicRecord{}
	mi := &file_clinic_clinic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicRecord) ProtoMessage() {}

func (x *ClinicRecord) ProtoReflect() protoreflect.Message {
	mi := &file_clinic_clinic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicRecord.ProtoReflect.Descriptor instead.
func (*ClinicRecord) Descriptor() ([]byte, []int) {
	return file_clinic_clinic_proto_rawDescGZIP(), []int{0}
}

func (x *ClinicRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClinicRecord) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *ClinicRecord) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ClinicRecord) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *ClinicRecord) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *ClinicRecord) GetChiefComplaint() string {
	if x != nil {
		return x.ChiefComplaint
	}
	return ""
}

func (x *ClinicRecord) GetPresentIllness() string {
	if x != nil {
		return x.PresentIllness
	}
	return ""
}

func (x *ClinicRecord) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *ClinicRecord) GetIcdCode() string {
	if x != nil {
		return x.IcdCode
	}
	return ""
}

func (x *ClinicRecord) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

func (x *ClinicRecord) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ClinicRecord) GetVisitTime() string {
	if x != nil {
		return x.VisitTime
	}
	return ""
}

func (x *ClinicRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 检查申请
type ExaminationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClinicRecordId    string                 `protobuf:"bytes,2,opt,name=clinic_record_id,json=clinicRecordId,proto3" json:"clinic_record_id,omitempty"`
	PatientId         string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ExamType          string                 `protobuf:"bytes,4,opt,name=exam_type,json=examType,proto3" json:"exam_type,omitempty"`
	ExamItem          string                 `protobuf:"bytes,5,opt,name=exam_item,json=examItem,proto3" json:"exam_item,omitempty"`
	BodyPart          string                 `protobuf:"bytes,6,opt,name=body_part,json=bodyPart,proto3" json:"body_part,omitempty"`
	ClinicalDiagnosis string                 `protobuf:"bytes,7,opt,name=clinical_diagnosis,json=clinicalDiagnosis,proto3" json:"clinical_diagnosis,omitempty"`
	Note              string                 `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
	Status            int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExaminationRequest) Reset() {
	*x = ExaminationRequest{}
	mi := &file_clinic_clinic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExaminationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExaminationRequest) ProtoMessage() {}

func (x *ExaminationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinic_clinic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExaminationRequest.ProtoReflect.Descriptor instead.
func (*ExaminationRequest) Descriptor() ([]byte, []int) {
	return file_clinic_clinic_proto_rawDescGZIP(), []int{1}
}

func (x *ExaminationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExaminationRequest) GetClinicRecordId() string {
	if x != nil {
		return x.ClinicRecordId
	}
	return ""
}

func (x *ExaminationRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ExaminationRequest) GetExamType() string {
	if x != nil {
		return x.ExamType
	}
	return ""
}

func (x *ExaminationRequest) GetExamItem() string {
	if x != nil {
		return x.ExamItem
	}
	return ""
}

func (x *ExaminationRequest) GetBodyPart() string {
	if x != nil {
		return x.BodyPart
	}
	return ""
}

func (x *ExaminationRequest) GetClinicalDiagnosis() string {
	if x != nil {
		return x.ClinicalDiagnosis
	}
	return ""
}

func (x *ExaminationRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ExaminationRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ClinicListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClinicListRequest) Reset() {
	*x = ClinicListRequest{}
	mi := &file_clinic_clinic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicListRequest) ProtoMessage() {}

func (x *ClinicListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinic_clinic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicListRequest.ProtoReflect.Descriptor instead.
func (*ClinicListRequest) Descriptor() ([]byte, []int) {
	return file_clinic_clinic_proto_rawDescGZIP(), []int{2}
}

func (x *ClinicListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ClinicListRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ClinicListRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *ClinicListRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ClinicListRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ClinicListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Records       []*ClinicRecord        `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClinicListResponse) Reset() {
	*x = ClinicListResponse{}
	mi := &file_clinic_clinic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicListResponse) ProtoMessage() {}

func (x *ClinicListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinic_clinic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicListResponse.ProtoReflect.Descriptor instead.
func (*ClinicListResponse) Descriptor() ([]byte, []int) {
	return file_clinic_clinic_proto_rawDescGZIP(), []int{3}
}

func (x *ClinicListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ClinicListResponse) GetRecords() []*ClinicRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ClinicListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_clinic_clinic_proto protoreflect.FileDescriptor

const file_clinic_clinic_proto_rawDesc = "" +
	"\n" +
	"\x13clinic/clinic.proto\x12\x06clinic\x1a\x13common/common.proto\"\x9f\x03\n" +
	"\fClinicRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fregistration_id\x18\x02 \x01(\tR\x0eregistrationId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12!\n" +
	"\fpatient_name\x18\x04 \x01(\tR\vpatientName\x12\x1b\n" +
	"\tdoctor_id\x18\x05 \x01(\tR\bdoctorId\x12'\n" +
	"\x0fchief_complaint\x18\x06 \x01(\tR\x0echiefComplaint\x12'\n" +
	"\x0fpresent_illness\x18\a \x01(\tR\x0epresentIllness\x12\x1c\n" +
	"\tdiagnosis\x18\b \x01(\tR\tdiagnosis\x12\x19\n" +
	"\bicd_code\x18\t \x01(\tR\aicdCode\x12\x16\n" +
	"\x06advice\x18\n" +
	" \x01(\tR\x06advice\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"visit_time\x18\f \x01(\tR\tvisitTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\"\x9f\x02\n" +
	"\x12ExaminationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10clinic_record_id\x18\x02 \x01(\tR\x0eclinicRecordId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12\x1b\n" +
	"\texam_type\x18\x04 \x01(\tR\bexamType\x12\x1b\n" +
	"\texam_item\x18\x05 \x01(\tR\bexamItem\x12\x1b\n" +
	"\tbody_part\x18\x06 \x01(\tR\bbodyPart\x12-\n" +
	"\x12clinical_diagnosis\x18\a \x01(\tR\x11clinicalDiagnosis\x12\x12\n" +
	"\x04note\x18\b \x01(\tR\x04note\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"\xb2\x01\n" +
	"\x11ClinicListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"\x98\x01\n" +
	"\x12ClinicListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12.\n" +
	"\arecords\x18\x02 \x03(\v2\x14.clinic.ClinicRecordR\arecords\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page2\xad\x02\n" +
	"\rClinicService\x12@\n" +
	"\x12CreateClinicRecord\x12\x14.clinic.ClinicRecord\x1a\x14.clinic.ClinicRecord\x12:\n" +
	"\x0fGetClinicRecord\x12\x11.common.IdRequest\x1a\x14.clinic.ClinicRecord\x12J\n" +
	"\x11ListClinicRecords\x12\x19.clinic.ClinicListRequest\x1a\x1a.clinic.ClinicListResponse\x12R\n" +
	"\x18CreateExaminationRequest\x12\x1a.clinic.ExaminationRequest\x1a\x1a.clinic.ExaminationRequestB\x19Z\x17his-go/api/proto/clinicb\x06proto3"

var (
	file_clinic_clinic_proto_rawDescOnce sync.Once
	file_clinic_clinic_proto_rawDescData []byte
)

func file_clinic_clinic_proto_rawDescGZIP() []byte {
	file_clinic_clinic_proto_rawDescOnce.Do(func() {
		file_clinic_clinic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clinic_clinic_proto_rawDesc), len(file_clinic_clinic_proto_rawDesc)))
	})
	return file_clinic_clinic_proto_rawDescData
}

var file_clinic_clinic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_clinic_clinic_proto_goTypes = []any{
	(*ClinicRecord)(nil),        // 0: clinic.ClinicRecord
	(*ExaminationRequest)(nil),  // 1: clinic.ExaminationRequest
	(*ClinicListRequest)(nil),   // 2: clinic.ClinicListRequest
	(*ClinicListResponse)(nil),  // 3: clinic.ClinicListResponse
	(*common.PageRequest)(nil),  // 4: common.PageRequest
	(*common.BaseResponse)(nil), // 5: common.BaseResponse
	(*common.PageResponse)(nil), // 6: common.PageResponse
	(*common.IdRequest)(nil),    // 7: common.IdRequest
}
var file_clinic_clinic_proto_depIdxs = []int32{
	4, // 0: clinic.ClinicListRequest.page:type_name -> common.PageRequest
	5, // 1: clinic.ClinicListResponse.base:type_name -> common.BaseResponse
	0, // 2: clinic.ClinicListResponse.records:type_name -> clinic.ClinicRecord
	6, // 3: clinic.ClinicListResponse.page:type_name -> common.PageResponse
	0, // 4: clinic.ClinicService.CreateClinicRecord:input_type -> clinic.ClinicRecord
	7, // 5: clinic.ClinicService.GetClinicRecord:input_type -> common.IdRequest
	2, // 6: clinic.ClinicService.ListClinicRecords:input_type -> clinic.ClinicListRequest
	1, // 7: clinic.ClinicService.CreateExaminationRequest:input_type -> clinic.ExaminationRequest
	0, // 8: clinic.ClinicService.CreateClinicRecord:output_type -> clinic.ClinicRecord
	0, // 9: clinic.ClinicService.GetClinicRecord:output_type -> clinic.ClinicRecord
	3, // 10: clinic.ClinicService.ListClinicRecords:output_type -> clinic.ClinicListResponse
	1, // 11: clinic.ClinicService.CreateExaminationRequest:output_type -> clinic.ExaminationRequest
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_clinic_clinic_proto_init() }
func file_clinic_clinic_proto_init() {
	if File_clinic_clinic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clinic_clinic_proto_rawDesc), len(file_clinic_clinic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clinic_clinic_proto_goTypes,
		DependencyIndexes: file_clinic_clinic_proto_depIdxs,
		MessageInfos:      file_clinic_clinic_proto_msgTypes,
	}.Build()
	File_clinic_clinic_proto = out.File
	file_clinic_clinic_proto_goTypes = nil
	file_clinic_clinic_proto_depIdxs = nil
}
