// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: system/system.proto

package system

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "his-go/api/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemService_ListDictTypes_FullMethodName     = "/system.SystemService/ListDictTypes"
	SystemService_ListDictItems_FullMethodName     = "/system.SystemService/ListDictItems"
	SystemService_CreateDictItem_FullMethodName    = "/system.SystemService/CreateDictItem"
	SystemService_ListParams_FullMethodName        = "/system.SystemService/ListParams"
	SystemService_UpdateParam_FullMethodName       = "/system.SystemService/UpdateParam"
	SystemService_ListOperationLogs_FullMethodName = "/system.SystemService/ListOperationLogs"
)

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 系统管理服务
type SystemServiceClient interface {
	// 字典管理
	ListDictTypes(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*DictTypeListResponse, error)
	ListDictItems(ctx context.Context, in *DictItemQueryRequest, opts ...grpc.CallOption) (*DictItemListResponse, error)
	CreateDictItem(ctx context.Context, in *DictItem, opts ...grpc.CallOption) (*DictItem, error)
	// 参数管理
	ListParams(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ParamListResponse, error)
	UpdateParam(ctx context.Context, in *SystemParam, opts ...grpc.CallOption) (*SystemParam, error)
	// 操作日志
	ListOperationLogs(ctx context.Context, in *LogListRequest, opts ...grpc.CallOption) (*LogListResponse, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) ListDictTypes(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*DictTypeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictTypeListResponse)
	err := c.cc.Invoke(ctx, SystemService_ListDictTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListDictItems(ctx context.Context, in *DictItemQueryRequest, opts ...grpc.CallOption) (*DictItemListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictItemListResponse)
	err := c.cc.Invoke(ctx, SystemService_ListDictItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CreateDictItem(ctx context.Context, in *DictItem, opts ...grpc.CallOption) (*DictItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictItem)
	err := c.cc.Invoke(ctx, SystemService_CreateDictItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListParams(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ParamListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParamListResponse)
	err := c.cc.Invoke(ctx, SystemService_ListParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UpdateParam(ctx context.Context, in *SystemParam, opts ...grpc.CallOption) (*SystemParam, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemParam)
	err := c.cc.Invoke(ctx, SystemService_UpdateParam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListOperationLogs(ctx context.Context, in *LogListRequest, opts ...grpc.CallOption) (*LogListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogListResponse)
	err := c.cc.Invoke(ctx, SystemService_ListOperationLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility.
//
// 系统管理服务
type SystemServiceServer interface {
	// 字典管理
	ListDictTypes(context.Context, *common.Empty) (*DictTypeListResponse, error)
	ListDictItems(context.Context, *DictItemQueryRequest) (*DictItemListResponse, error)
	CreateDictItem(context.Context, *DictItem) (*DictItem, error)
	// 参数管理
	ListParams(context.Context, *common.Empty) (*ParamListResponse, error)
	UpdateParam(context.Context, *SystemParam) (*SystemParam, error)
	// 操作日志
	ListOperationLogs(context.Context, *LogListRequest) (*LogListResponse, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemServiceServer struct{}

func (UnimplementedSystemServiceServer) ListDictTypes(context.Context, *common.Empty) (*DictTypeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDictTypes not implemented")
}
func (UnimplementedSystemServiceServer) ListDictItems(context.Context, *DictItemQueryRequest) (*DictItemListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDictItems not implemented")
}
func (UnimplementedSystemServiceServer) CreateDictItem(context.Context, *DictItem) (*DictItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDictItem not implemented")
}
func (UnimplementedSystemServiceServer) ListParams(context.Context, *common.Empty) (*ParamListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListParams not implemented")
}
func (UnimplementedSystemServiceServer) UpdateParam(context.Context, *SystemParam) (*SystemParam, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateParam not implemented")
}
func (UnimplementedSystemServiceServer) ListOperationLogs(context.Context, *LogListRequest) (*LogListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOperationLogs not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}
func (UnimplementedSystemServiceServer) testEmbeddedByValue()                       {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_ListDictTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListDictTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_ListDictTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListDictTypes(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListDictItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictItemQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListDictItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_ListDictItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListDictItems(ctx, req.(*DictItemQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CreateDictItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CreateDictItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_CreateDictItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CreateDictItem(ctx, req.(*DictItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_ListParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListParams(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UpdateParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UpdateParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_UpdateParam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UpdateParam(ctx, req.(*SystemParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListOperationLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListOperationLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_ListOperationLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListOperationLogs(ctx, req.(*LogListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDictTypes",
			Handler:    _SystemService_ListDictTypes_Handler,
		},
		{
			MethodName: "ListDictItems",
			Handler:    _SystemService_ListDictItems_Handler,
		},
		{
			MethodName: "CreateDictItem",
			Handler:    _SystemService_CreateDictItem_Handler,
		},
		{
			MethodName: "ListParams",
			Handler:    _SystemService_ListParams_Handler,
		},
		{
			MethodName: "UpdateParam",
			Handler:    _SystemService_UpdateParam_Handler,
		},
		{
			MethodName: "ListOperationLogs",
			Handler:    _SystemService_ListOperationLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system/system.proto",
}
