// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: system/system.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 字典类型
type DictType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DictName      string                 `protobuf:"bytes,2,opt,name=dict_name,json=dictName,proto3" json:"dict_name,omitempty"`
	DictType      string                 `protobuf:"bytes,3,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictType) Reset() {
	*x = DictType{}
	mi := &file_system_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictType) ProtoMessage() {}

func (x *DictType) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictType.ProtoReflect.Descriptor instead.
func (*DictType) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{0}
}

func (x *DictType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DictType) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *DictType) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictType) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DictType) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 字典项
type DictItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DictType      string                 `protobuf:"bytes,2,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictItem) Reset() {
	*x = DictItem{}
	mi := &file_system_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictItem) ProtoMessage() {}

func (x *DictItem) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictItem.ProtoReflect.Descriptor instead.
func (*DictItem) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{1}
}

func (x *DictItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DictItem) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DictItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DictItem) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *DictItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 操作日志
type OperationLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Module        string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Ip            string                 `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	Params        string                 `protobuf:"bytes,9,opt,name=params,proto3" json:"params,omitempty"`
	Result        string                 `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLog) Reset() {
	*x = OperationLog{}
	mi := &file_system_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLog) ProtoMessage() {}

func (x *OperationLog) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLog.ProtoReflect.Descriptor instead.
func (*OperationLog) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{2}
}

func (x *OperationLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OperationLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OperationLog) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OperationLog) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *OperationLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *OperationLog) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OperationLog) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OperationLog) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OperationLog) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *OperationLog) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *OperationLog) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OperationLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 系统参数
type SystemParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParamName     string                 `protobuf:"bytes,2,opt,name=param_name,json=paramName,proto3" json:"param_name,omitempty"`
	ParamKey      string                 `protobuf:"bytes,3,opt,name=param_key,json=paramKey,proto3" json:"param_key,omitempty"`
	ParamValue    string                 `protobuf:"bytes,4,opt,name=param_value,json=paramValue,proto3" json:"param_value,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemParam) Reset() {
	*x = SystemParam{}
	mi := &file_system_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemParam) ProtoMessage() {}

func (x *SystemParam) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemParam.ProtoReflect.Descriptor instead.
func (*SystemParam) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{3}
}

func (x *SystemParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SystemParam) GetParamName() string {
	if x != nil {
		return x.ParamName
	}
	return ""
}

func (x *SystemParam) GetParamKey() string {
	if x != nil {
		return x.ParamKey
	}
	return ""
}

func (x *SystemParam) GetParamValue() string {
	if x != nil {
		return x.ParamValue
	}
	return ""
}

func (x *SystemParam) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type DictTypeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Types         []*DictType            `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictTypeListResponse) Reset() {
	*x = DictTypeListResponse{}
	mi := &file_system_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictTypeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictTypeListResponse) ProtoMessage() {}

func (x *DictTypeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictTypeListResponse.ProtoReflect.Descriptor instead.
func (*DictTypeListResponse) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{4}
}

func (x *DictTypeListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DictTypeListResponse) GetTypes() []*DictType {
	if x != nil {
		return x.Types
	}
	return nil
}

type DictItemQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictType      string                 `protobuf:"bytes,1,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictItemQueryRequest) Reset() {
	*x = DictItemQueryRequest{}
	mi := &file_system_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictItemQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictItemQueryRequest) ProtoMessage() {}

func (x *DictItemQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictItemQueryRequest.ProtoReflect.Descriptor instead.
func (*DictItemQueryRequest) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{5}
}

func (x *DictItemQueryRequest) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

type DictItemListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Items         []*DictItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictItemListResponse) Reset() {
	*x = DictItemListResponse{}
	mi := &file_system_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictItemListResponse) ProtoMessage() {}

func (x *DictItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictItemListResponse.ProtoReflect.Descriptor instead.
func (*DictItemListResponse) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{6}
}

func (x *DictItemListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DictItemListResponse) GetItems() []*DictItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ParamListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Params        []*SystemParam         `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamListResponse) Reset() {
	*x = ParamListResponse{}
	mi := &file_system_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamListResponse) ProtoMessage() {}

func (x *ParamListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamListResponse.ProtoReflect.Descriptor instead.
func (*ParamListResponse) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{7}
}

func (x *ParamListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ParamListResponse) GetParams() []*SystemParam {
	if x != nil {
		return x.Params
	}
	return nil
}

type LogListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Module        string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogListRequest) Reset() {
	*x = LogListRequest{}
	mi := &file_system_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogListRequest) ProtoMessage() {}

func (x *LogListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogListRequest.ProtoReflect.Descriptor instead.
func (*LogListRequest) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{8}
}

func (x *LogListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *LogListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogListRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *LogListRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *LogListRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type LogListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Logs          []*OperationLog        `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogListResponse) Reset() {
	*x = LogListResponse{}
	mi := &file_system_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogListResponse) ProtoMessage() {}

func (x *LogListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogListResponse.ProtoReflect.Descriptor instead.
func (*LogListResponse) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{9}
}

func (x *LogListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *LogListResponse) GetLogs() []*OperationLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *LogListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_system_system_proto protoreflect.FileDescriptor

const file_system_system_proto_rawDesc = "" +
	"\n" +
	"\x13system/system.proto\x12\x06system\x1a\x13common/common.proto\"\x84\x01\n" +
	"\bDictType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdict_name\x18\x02 \x01(\tR\bdictName\x12\x1b\n" +
	"\tdict_type\x18\x03 \x01(\tR\bdictType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\"\x9a\x01\n" +
	"\bDictItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdict_type\x18\x02 \x01(\tR\bdictType\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"\xa4\x02\n" +
	"\fOperationLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06module\x18\x04 \x01(\tR\x06module\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12\x0e\n" +
	"\x02ip\x18\b \x01(\tR\x02ip\x12\x16\n" +
	"\x06params\x18\t \x01(\tR\x06params\x12\x16\n" +
	"\x06result\x18\n" +
	" \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"\x92\x01\n" +
	"\vSystemParam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"param_name\x18\x02 \x01(\tR\tparamName\x12\x1b\n" +
	"\tparam_key\x18\x03 \x01(\tR\bparamKey\x12\x1f\n" +
	"\vparam_value\x18\x04 \x01(\tR\n" +
	"paramValue\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\"h\n" +
	"\x14DictTypeListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12&\n" +
	"\x05types\x18\x02 \x03(\v2\x10.system.DictTypeR\x05types\"3\n" +
	"\x14DictItemQueryRequest\x12\x1b\n" +
	"\tdict_type\x18\x01 \x01(\tR\bdictType\"h\n" +
	"\x14DictItemListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12&\n" +
	"\x05items\x18\x02 \x03(\v2\x10.system.DictItemR\x05items\"j\n" +
	"\x11ParamListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12+\n" +
	"\x06params\x18\x02 \x03(\v2\x13.system.SystemParamR\x06params\"\xa4\x01\n" +
	"\x0eLogListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"\x8f\x01\n" +
	"\x0fLogListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12(\n" +
	"\x04logs\x18\x02 \x03(\v2\x14.system.OperationLogR\x04logs\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page2\x87\x03\n" +
	"\rSystemService\x12<\n" +
	"\rListDictTypes\x12\r.common.Empty\x1a\x1c.system.DictTypeListResponse\x12K\n" +
	"\rListDictItems\x12\x1c.system.DictItemQueryRequest\x1a\x1c.system.DictItemListResponse\x124\n" +
	"\x0eCreateDictItem\x12\x10.system.DictItem\x1a\x10.system.DictItem\x126\n" +
	"\n" +
	"ListParams\x12\r.common.Empty\x1a\x19.system.ParamListResponse\x127\n" +
	"\vUpdateParam\x12\x13.system.SystemParam\x1a\x13.system.SystemParam\x12D\n" +
	"\x11ListOperationLogs\x12\x16.system.LogListRequest\x1a\x17.system.LogListResponseB\x19Z\x17his-go/api/proto/systemb\x06proto3"

var (
	file_system_system_proto_rawDescOnce sync.Once
	file_system_system_proto_rawDescData []byte
)

func file_system_system_proto_rawDescGZIP() []byte {
	file_system_system_proto_rawDescOnce.Do(func() {
		file_system_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_system_proto_rawDesc), len(file_system_system_proto_rawDesc)))
	})
	return file_system_system_proto_rawDescData
}

var file_system_system_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_system_system_proto_goTypes = []any{
	(*DictType)(nil),             // 0: system.DictType
	(*DictItem)(nil),             // 1: system.DictItem
	(*OperationLog)(nil),         // 2: system.OperationLog
	(*SystemParam)(nil),          // 3: system.SystemParam
	(*DictTypeListResponse)(nil), // 4: system.DictTypeListResponse
	(*DictItemQueryRequest)(nil), // 5: system.DictItemQueryRequest
	(*DictItemListResponse)(nil), // 6: system.DictItemListResponse
	(*ParamListResponse)(nil),    // 7: system.ParamListResponse
	(*LogListRequest)(nil),       // 8: system.LogListRequest
	(*LogListResponse)(nil),      // 9: system.LogListResponse
	(*common.BaseResponse)(nil),  // 10: common.BaseResponse
	(*common.PageRequest)(nil),   // 11: common.PageRequest
	(*common.PageResponse)(nil),  // 12: common.PageResponse
	(*common.Empty)(nil),         // 13: common.Empty
}
var file_system_system_proto_depIdxs = []int32{
	10, // 0: system.DictTypeListResponse.base:type_name -> common.BaseResponse
	0,  // 1: system.DictTypeListResponse.types:type_name -> system.DictType
	10, // 2: system.DictItemListResponse.base:type_name -> common.BaseResponse
	1,  // 3: system.DictItemListResponse.items:type_name -> system.DictItem
	10, // 4: system.ParamListResponse.base:type_name -> common.BaseResponse
	3,  // 5: system.ParamListResponse.params:type_name -> system.SystemParam
	11, // 6: system.LogListRequest.page:type_name -> common.PageRequest
	10, // 7: system.LogListResponse.base:type_name -> common.BaseResponse
	2,  // 8: system.LogListResponse.logs:type_name -> system.OperationLog
	12, // 9: system.LogListResponse.page:type_name -> common.PageResponse
	13, // 10: system.SystemService.ListDictTypes:input_type -> common.Empty
	5,  // 11: system.SystemService.ListDictItems:input_type -> system.DictItemQueryRequest
	1,  // 12: system.SystemService.CreateDictItem:input_type -> system.DictItem
	13, // 13: system.SystemService.ListParams:input_type -> common.Empty
	3,  // 14: system.SystemService.UpdateParam:input_type -> system.SystemParam
	8,  // 15: system.SystemService.ListOperationLogs:input_type -> system.LogListRequest
	4,  // 16: system.SystemService.ListDictTypes:output_type -> system.DictTypeListResponse
	6,  // 17: system.SystemService.ListDictItems:output_type -> system.DictItemListResponse
	1,  // 18: system.SystemService.CreateDictItem:output_type -> system.DictItem
	7,  // 19: system.SystemService.ListParams:output_type -> system.ParamListResponse
	3,  // 20: system.SystemService.UpdateParam:output_type -> system.SystemParam
	9,  // 21: system.SystemService.ListOperationLogs:output_type -> system.LogListResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_system_system_proto_init() }
func file_system_system_proto_init() {
	if File_system_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_system_proto_rawDesc), len(file_system_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_system_proto_goTypes,
		DependencyIndexes: file_system_system_proto_depIdxs,
		MessageInfos:      file_system_system_proto_msgTypes,
	}.Build()
	File_system_system_proto = out.File
	file_system_system_proto_goTypes = nil
	file_system_system_proto_depIdxs = nil
}
