// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: emr/emr.proto

package emr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 病历记录
type MedicalRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId      string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ClinicRecordId string                 `protobuf:"bytes,3,opt,name=clinic_record_id,json=clinicRecordId,proto3" json:"clinic_record_id,omitempty"`
	TemplateId     string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ChiefComplaint string                 `protobuf:"bytes,5,opt,name=chief_complaint,json=chiefComplaint,proto3" json:"chief_complaint,omitempty"` // 主诉
	PresentIllness string                 `protobuf:"bytes,6,opt,name=present_illness,json=presentIllness,proto3" json:"present_illness,omitempty"` // 现病史
	PastHistory    string                 `protobuf:"bytes,7,opt,name=past_history,json=pastHistory,proto3" json:"past_history,omitempty"`          // 既往史
	PhysicalExam   string                 `protobuf:"bytes,8,opt,name=physical_exam,json=physicalExam,proto3" json:"physical_exam,omitempty"`       // 体格检查
	AuxiliaryExam  string                 `protobuf:"bytes,9,opt,name=auxiliary_exam,json=auxiliaryExam,proto3" json:"auxiliary_exam,omitempty"`    // 辅助检查
	Diagnosis      string                 `protobuf:"bytes,10,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`                                // 诊断
	TreatmentPlan  string                 `protobuf:"bytes,11,opt,name=treatment_plan,json=treatmentPlan,proto3" json:"treatment_plan,omitempty"`   // 处理计划
	QualityLevel   int32                  `protobuf:"varint,12,opt,name=quality_level,json=qualityLevel,proto3" json:"quality_level,omitempty"`     // 质控等级
	Status         int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`                                     // 0-草稿 1-已完成 2-已质控 3-已归档
	CreatedAt      string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MedicalRecord) Reset() {
	*x = MedicalRecord{}
	mi := &file_emr_emr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedicalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedicalRecord) ProtoMessage() {}

func (x *MedicalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedicalRecord.ProtoReflect.Descriptor instead.
func (*MedicalRecord) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{0}
}

func (x *MedicalRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MedicalRecord) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *MedicalRecord) GetClinicRecordId() string {
	if x != nil {
		return x.ClinicRecordId
	}
	return ""
}

func (x *MedicalRecord) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *MedicalRecord) GetChiefComplaint() string {
	if x != nil {
		return x.ChiefComplaint
	}
	return ""
}

func (x *MedicalRecord) GetPresentIllness() string {
	if x != nil {
		return x.PresentIllness
	}
	return ""
}

func (x *MedicalRecord) GetPastHistory() string {
	if x != nil {
		return x.PastHistory
	}
	return ""
}

func (x *MedicalRecord) GetPhysicalExam() string {
	if x != nil {
		return x.PhysicalExam
	}
	return ""
}

func (x *MedicalRecord) GetAuxiliaryExam() string {
	if x != nil {
		return x.AuxiliaryExam
	}
	return ""
}

func (x *MedicalRecord) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *MedicalRecord) GetTreatmentPlan() string {
	if x != nil {
		return x.TreatmentPlan
	}
	return ""
}

func (x *MedicalRecord) GetQualityLevel() int32 {
	if x != nil {
		return x.QualityLevel
	}
	return 0
}

func (x *MedicalRecord) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MedicalRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 病历模板
type RecordTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeptId        string                 `protobuf:"bytes,3,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTemplate) Reset() {
	*x = RecordTemplate{}
	mi := &file_emr_emr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTemplate) ProtoMessage() {}

func (x *RecordTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTemplate.ProtoReflect.Descriptor instead.
func (*RecordTemplate) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{1}
}

func (x *RecordTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecordTemplate) GetDeptId() string {
	if x != nil {
		return x.DeptId
	}
	return ""
}

func (x *RecordTemplate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RecordTemplate) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// CDSS 校验请求
type CDSSCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DrugId        string                 `protobuf:"bytes,2,opt,name=drug_id,json=drugId,proto3" json:"drug_id,omitempty"`
	Diagnosis     string                 `protobuf:"bytes,3,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDSSCheckRequest) Reset() {
	*x = CDSSCheckRequest{}
	mi := &file_emr_emr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDSSCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDSSCheckRequest) ProtoMessage() {}

func (x *CDSSCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDSSCheckRequest.ProtoReflect.Descriptor instead.
func (*CDSSCheckRequest) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{2}
}

func (x *CDSSCheckRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *CDSSCheckRequest) GetDrugId() string {
	if x != nil {
		return x.DrugId
	}
	return ""
}

func (x *CDSSCheckRequest) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

// CDSS 校验结果
type CDSSCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Safe          bool                   `protobuf:"varint,1,opt,name=safe,proto3" json:"safe,omitempty"`
	Warnings      []string               `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Suggestions   []string               `protobuf:"bytes,3,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDSSCheckResult) Reset() {
	*x = CDSSCheckResult{}
	mi := &file_emr_emr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDSSCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDSSCheckResult) ProtoMessage() {}

func (x *CDSSCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDSSCheckResult.ProtoReflect.Descriptor instead.
func (*CDSSCheckResult) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{3}
}

func (x *CDSSCheckResult) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *CDSSCheckResult) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *CDSSCheckResult) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type RecordListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordListRequest) Reset() {
	*x = RecordListRequest{}
	mi := &file_emr_emr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordListRequest) ProtoMessage() {}

func (x *RecordListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordListRequest.ProtoReflect.Descriptor instead.
func (*RecordListRequest) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{4}
}

func (x *RecordListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *RecordListRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *RecordListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RecordListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Records       []*MedicalRecord       `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordListResponse) Reset() {
	*x = RecordListResponse{}
	mi := &file_emr_emr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordListResponse) ProtoMessage() {}

func (x *RecordListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordListResponse.ProtoReflect.Descriptor instead.
func (*RecordListResponse) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{5}
}

func (x *RecordListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RecordListResponse) GetRecords() []*MedicalRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *RecordListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type TemplateListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Templates     []*RecordTemplate      `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateListResponse) Reset() {
	*x = TemplateListResponse{}
	mi := &file_emr_emr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateListResponse) ProtoMessage() {}

func (x *TemplateListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emr_emr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateListResponse.ProtoReflect.Descriptor instead.
func (*TemplateListResponse) Descriptor() ([]byte, []int) {
	return file_emr_emr_proto_rawDescGZIP(), []int{6}
}

func (x *TemplateListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *TemplateListResponse) GetTemplates() []*RecordTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

var File_emr_emr_proto protoreflect.FileDescriptor

const file_emr_emr_proto_rawDesc = "" +
	"\n" +
	"\remr/emr.proto\x12\x03emr\x1a\x13common/common.proto\"\xeb\x03\n" +
	"\rMedicalRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12(\n" +
	"\x10clinic_record_id\x18\x03 \x01(\tR\x0eclinicRecordId\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\x12'\n" +
	"\x0fchief_complaint\x18\x05 \x01(\tR\x0echiefComplaint\x12'\n" +
	"\x0fpresent_illness\x18\x06 \x01(\tR\x0epresentIllness\x12!\n" +
	"\fpast_history\x18\a \x01(\tR\vpastHistory\x12#\n" +
	"\rphysical_exam\x18\b \x01(\tR\fphysicalExam\x12%\n" +
	"\x0eauxiliary_exam\x18\t \x01(\tR\rauxiliaryExam\x12\x1c\n" +
	"\tdiagnosis\x18\n" +
	" \x01(\tR\tdiagnosis\x12%\n" +
	"\x0etreatment_plan\x18\v \x01(\tR\rtreatmentPlan\x12#\n" +
	"\rquality_level\x18\f \x01(\x05R\fqualityLevel\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\"{\n" +
	"\x0eRecordTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\adept_id\x18\x03 \x01(\tR\x06deptId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\"h\n" +
	"\x10CDSSCheckRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x17\n" +
	"\adrug_id\x18\x02 \x01(\tR\x06drugId\x12\x1c\n" +
	"\tdiagnosis\x18\x03 \x01(\tR\tdiagnosis\"c\n" +
	"\x0fCDSSCheckResult\x12\x12\n" +
	"\x04safe\x18\x01 \x01(\bR\x04safe\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings\x12 \n" +
	"\vsuggestions\x18\x03 \x03(\tR\vsuggestions\"s\n" +
	"\x11RecordListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\x96\x01\n" +
	"\x12RecordListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12,\n" +
	"\arecords\x18\x02 \x03(\v2\x12.emr.MedicalRecordR\arecords\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page\"s\n" +
	"\x14TemplateListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x121\n" +
	"\ttemplates\x18\x02 \x03(\v2\x13.emr.RecordTemplateR\ttemplates2\xe6\x02\n" +
	"\n" +
	"EMRService\x126\n" +
	"\fCreateRecord\x12\x12.emr.MedicalRecord\x1a\x12.emr.MedicalRecord\x122\n" +
	"\tGetRecord\x12\x11.common.IdRequest\x1a\x12.emr.MedicalRecord\x12>\n" +
	"\vListRecords\x12\x16.emr.RecordListRequest\x1a\x17.emr.RecordListResponse\x127\n" +
	"\x0eQualityControl\x12\x11.common.IdRequest\x1a\x12.emr.MedicalRecord\x129\n" +
	"\rListTemplates\x12\r.common.Empty\x1a\x19.emr.TemplateListResponse\x128\n" +
	"\tCDSSCheck\x12\x15.emr.CDSSCheckRequest\x1a\x14.emr.CDSSCheckResultB\x16Z\x14his-go/api/proto/emrb\x06proto3"

var (
	file_emr_emr_proto_rawDescOnce sync.Once
	file_emr_emr_proto_rawDescData []byte
)

func file_emr_emr_proto_rawDescGZIP() []byte {
	file_emr_emr_proto_rawDescOnce.Do(func() {
		file_emr_emr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emr_emr_proto_rawDesc), len(file_emr_emr_proto_rawDesc)))
	})
	return file_emr_emr_proto_rawDescData
}

var file_emr_emr_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_emr_emr_proto_goTypes = []any{
	(*MedicalRecord)(nil),        // 0: emr.MedicalRecord
	(*RecordTemplate)(nil),       // 1: emr.RecordTemplate
	(*CDSSCheckRequest)(nil),     // 2: emr.CDSSCheckRequest
	(*CDSSCheckResult)(nil),      // 3: emr.CDSSCheckResult
	(*RecordListRequest)(nil),    // 4: emr.RecordListRequest
	(*RecordListResponse)(nil),   // 5: emr.RecordListResponse
	(*TemplateListResponse)(nil), // 6: emr.TemplateListResponse
	(*common.PageRequest)(nil),   // 7: common.PageRequest
	(*common.BaseResponse)(nil),  // 8: common.BaseResponse
	(*common.PageResponse)(nil),  // 9: common.PageResponse
	(*common.IdRequest)(nil),     // 10: common.IdRequest
	(*common.Empty)(nil),         // 11: common.Empty
}
var file_emr_emr_proto_depIdxs = []int32{
	7,  // 0: emr.RecordListRequest.page:type_name -> common.PageRequest
	8,  // 1: emr.RecordListResponse.base:type_name -> common.BaseResponse
	0,  // 2: emr.RecordListResponse.records:type_name -> emr.MedicalRecord
	9,  // 3: emr.RecordListResponse.page:type_name -> common.PageResponse
	8,  // 4: emr.TemplateListResponse.base:type_name -> common.BaseResponse
	1,  // 5: emr.TemplateListResponse.templates:type_name -> emr.RecordTemplate
	0,  // 6: emr.EMRService.CreateRecord:input_type -> emr.MedicalRecord
	10, // 7: emr.EMRService.GetRecord:input_type -> common.IdRequest
	4,  // 8: emr.EMRService.ListRecords:input_type -> emr.RecordListRequest
	10, // 9: emr.EMRService.QualityControl:input_type -> common.IdRequest
	11, // 10: emr.EMRService.ListTemplates:input_type -> common.Empty
	2,  // 11: emr.EMRService.CDSSCheck:input_type -> emr.CDSSCheckRequest
	0,  // 12: emr.EMRService.CreateRecord:output_type -> emr.MedicalRecord
	0,  // 13: emr.EMRService.GetRecord:output_type -> emr.MedicalRecord
	5,  // 14: emr.EMRService.ListRecords:output_type -> emr.RecordListResponse
	0,  // 15: emr.EMRService.QualityControl:output_type -> emr.MedicalRecord
	6,  // 16: emr.EMRService.ListTemplates:output_type -> emr.TemplateListResponse
	3,  // 17: emr.EMRService.CDSSCheck:output_type -> emr.CDSSCheckResult
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_emr_emr_proto_init() }
func file_emr_emr_proto_init() {
	if File_emr_emr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emr_emr_proto_rawDesc), len(file_emr_emr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emr_emr_proto_goTypes,
		DependencyIndexes: file_emr_emr_proto_depIdxs,
		MessageInfos:      file_emr_emr_proto_msgTypes,
	}.Build()
	File_emr_emr_proto = out.File
	file_emr_emr_proto_goTypes = nil
	file_emr_emr_proto_depIdxs = nil
}
