// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: emr/emr.proto

package emr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "his-go/api/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EMRService_CreateRecord_FullMethodName   = "/emr.EMRService/CreateRecord"
	EMRService_GetRecord_FullMethodName      = "/emr.EMRService/GetRecord"
	EMRService_ListRecords_FullMethodName    = "/emr.EMRService/ListRecords"
	EMRService_QualityControl_FullMethodName = "/emr.EMRService/QualityControl"
	EMRService_ListTemplates_FullMethodName  = "/emr.EMRService/ListTemplates"
	EMRService_CDSSCheck_FullMethodName      = "/emr.EMRService/CDSSCheck"
)

// EMRServiceClient is the client API for EMRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 电子病历服务
type EMRServiceClient interface {
	CreateRecord(ctx context.Context, in *MedicalRecord, opts ...grpc.CallOption) (*MedicalRecord, error)
	GetRecord(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*MedicalRecord, error)
	ListRecords(ctx context.Context, in *RecordListRequest, opts ...grpc.CallOption) (*RecordListResponse, error)
	QualityControl(ctx context.Context, in *QualityControlRequest, opts ...grpc.CallOption) (*MedicalRecord, error)
	ListTemplates(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*TemplateListResponse, error)
	CDSSCheck(ctx context.Context, in *CDSSCheckRequest, opts ...grpc.CallOption) (*CDSSCheckResult, error)
}

type eMRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEMRServiceClient(cc grpc.ClientConnInterface) EMRServiceClient {
	return &eMRServiceClient{cc}
}

func (c *eMRServiceClient) CreateRecord(ctx context.Context, in *MedicalRecord, opts ...grpc.CallOption) (*MedicalRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MedicalRecord)
	err := c.cc.Invoke(ctx, EMRService_CreateRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) GetRecord(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*MedicalRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MedicalRecord)
	err := c.cc.Invoke(ctx, EMRService_GetRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) ListRecords(ctx context.Context, in *RecordListRequest, opts ...grpc.CallOption) (*RecordListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordListResponse)
	err := c.cc.Invoke(ctx, EMRService_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) QualityControl(ctx context.Context, in *QualityControlRequest, opts ...grpc.CallOption) (*MedicalRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MedicalRecord)
	err := c.cc.Invoke(ctx, EMRService_QualityControl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) ListTemplates(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*TemplateListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateListResponse)
	err := c.cc.Invoke(ctx, EMRService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eMRServiceClient) CDSSCheck(ctx context.Context, in *CDSSCheckRequest, opts ...grpc.CallOption) (*CDSSCheckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CDSSCheckResult)
	err := c.cc.Invoke(ctx, EMRService_CDSSCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EMRServiceServer is the server API for EMRService service.
// All implementations must embed UnimplementedEMRServiceServer
// for forward compatibility.
//
// 电子病历服务
type EMRServiceServer interface {
	CreateRecord(context.Context, *MedicalRecord) (*MedicalRecord, error)
	GetRecord(context.Context, *common.IdRequest) (*MedicalRecord, error)
	ListRecords(context.Context, *RecordListRequest) (*RecordListResponse, error)
	QualityControl(context.Context, *QualityControlRequest) (*MedicalRecord, error)
	ListTemplates(context.Context, *common.Empty) (*TemplateListResponse, error)
	CDSSCheck(context.Context, *CDSSCheckRequest) (*CDSSCheckResult, error)
	mustEmbedUnimplementedEMRServiceServer()
}

// UnimplementedEMRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEMRServiceServer struct{}

func (UnimplementedEMRServiceServer) CreateRecord(context.Context, *MedicalRecord) (*MedicalRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRecord not implemented")
}
func (UnimplementedEMRServiceServer) GetRecord(context.Context, *common.IdRequest) (*MedicalRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedEMRServiceServer) ListRecords(context.Context, *RecordListRequest) (*RecordListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedEMRServiceServer) QualityControl(context.Context, *QualityControlRequest) (*MedicalRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method QualityControl not implemented")
}
func (UnimplementedEMRServiceServer) ListTemplates(context.Context, *common.Empty) (*TemplateListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedEMRServiceServer) CDSSCheck(context.Context, *CDSSCheckRequest) (*CDSSCheckResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CDSSCheck not implemented")
}
func (UnimplementedEMRServiceServer) mustEmbedUnimplementedEMRServiceServer() {}
func (UnimplementedEMRServiceServer) testEmbeddedByValue()                    {}

// UnsafeEMRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EMRServiceServer will
// result in compilation errors.
type UnsafeEMRServiceServer interface {
	mustEmbedUnimplementedEMRServiceServer()
}

func RegisterEMRServiceServer(s grpc.ServiceRegistrar, srv EMRServiceServer) {
	// If the following call panics, it indicates UnimplementedEMRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EMRService_ServiceDesc, srv)
}

func _EMRService_CreateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MedicalRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).CreateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_CreateRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).CreateRecord(ctx, req.(*MedicalRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_GetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).GetRecord(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).ListRecords(ctx, req.(*RecordListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_QualityControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QualityControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).QualityControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_QualityControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).QualityControl(ctx, req.(*QualityControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).ListTemplates(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EMRService_CDSSCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CDSSCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EMRServiceServer).CDSSCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EMRService_CDSSCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EMRServiceServer).CDSSCheck(ctx, req.(*CDSSCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EMRService_ServiceDesc is the grpc.ServiceDesc for EMRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EMRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emr.EMRService",
	HandlerType: (*EMRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRecord",
			Handler:    _EMRService_CreateRecord_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _EMRService_GetRecord_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _EMRService_ListRecords_Handler,
		},
		{
			MethodName: "QualityControl",
			Handler:    _EMRService_QualityControl_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _EMRService_ListTemplates_Handler,
		},
		{
			MethodName: "CDSSCheck",
			Handler:    _EMRService_CDSSCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emr/emr.proto",
}
