// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: followup/followup.proto

package followup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 随访计划
type FollowupPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	PlanName      string                 `protobuf:"bytes,4,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Frequency     int32                  `protobuf:"varint,7,opt,name=frequency,proto3" json:"frequency,omitempty"` // 1-每周 2-每两周 3-每月
	Tasks         []*FollowupTask        `protobuf:"bytes,8,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowupPlan) Reset() {
	*x = FollowupPlan{}
	mi := &file_followup_followup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowupPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowupPlan) ProtoMessage() {}

func (x *FollowupPlan) ProtoReflect() protoreflect.Message {
	mi := &file_followup_followup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowupPlan.ProtoReflect.Descriptor instead.
func (*FollowupPlan) Descriptor() ([]byte, []int) {
	return file_followup_followup_proto_rawDescGZIP(), []int{0}
}

func (x *FollowupPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FollowupPlan) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *FollowupPlan) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *FollowupPlan) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *FollowupPlan) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *FollowupPlan) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *FollowupPlan) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *FollowupPlan) GetTasks() []*FollowupTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *FollowupPlan) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 随访任务
type FollowupTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,3,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	ExecuteDate   string                 `protobuf:"bytes,4,opt,name=execute_date,json=executeDate,proto3" json:"execute_date,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"` // 1-电话 2-问卷 3-上门
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowupTask) Reset() {
	*x = FollowupTask{}
	mi := &file_followup_followup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowupTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowupTask) ProtoMessage() {}

func (x *FollowupTask) ProtoReflect() protoreflect.Message {
	mi := &file_followup_followup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowupTask.ProtoReflect.Descriptor instead.
func (*FollowupTask) Descriptor() ([]byte, []int) {
	return file_followup_followup_proto_rawDescGZIP(), []int{1}
}

func (x *FollowupTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FollowupTask) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *FollowupTask) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *FollowupTask) GetExecuteDate() string {
	if x != nil {
		return x.ExecuteDate
	}
	return ""
}

func (x *FollowupTask) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *FollowupTask) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FollowupTask) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 满意度调查
type SatisfactionSurvey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FollowupTaskId string                 `protobuf:"bytes,2,opt,name=followup_task_id,json=followupTaskId,proto3" json:"followup_task_id,omitempty"`
	PatientId      string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Score          int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Feedback       string                 `protobuf:"bytes,5,opt,name=feedback,proto3" json:"feedback,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SatisfactionSurvey) Reset() {
	*x = SatisfactionSurvey{}
	mi := &file_followup_followup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatisfactionSurvey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatisfactionSurvey) ProtoMessage() {}

func (x *SatisfactionSurvey) ProtoReflect() protoreflect.Message {
	mi := &file_followup_followup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatisfactionSurvey.ProtoReflect.Descriptor instead.
func (*SatisfactionSurvey) Descriptor() ([]byte, []int) {
	return file_followup_followup_proto_rawDescGZIP(), []int{2}
}

func (x *SatisfactionSurvey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SatisfactionSurvey) GetFollowupTaskId() string {
	if x != nil {
		return x.FollowupTaskId
	}
	return ""
}

func (x *SatisfactionSurvey) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *SatisfactionSurvey) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SatisfactionSurvey) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *SatisfactionSurvey) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ExecuteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_followup_followup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_followup_followup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_followup_followup_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type PlanListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanListRequest) Reset() {
	*x = PlanListRequest{}
	mi := &file_followup_followup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanListRequest) ProtoMessage() {}

func (x *PlanListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_followup_followup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanListRequest.ProtoReflect.Descriptor instead.
func (*PlanListRequest) Descriptor() ([]byte, []int) {
	return file_followup_followup_proto_rawDescGZIP(), []int{4}
}

func (x *PlanListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PlanListRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *PlanListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PlanListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Plans         []*FollowupPlan        `protobuf:"bytes,2,rep,name=plans,proto3" json:"plans,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanListResponse) Reset() {
	*x = PlanListResponse{}
	mi := &file_followup_followup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanListResponse) ProtoMessage() {}

func (x *PlanListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_followup_followup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanListResponse.ProtoReflect.Descriptor instead.
func (*PlanListResponse) Descriptor() ([]byte, []int) {
	return file_followup_followup_proto_rawDescGZIP(), []int{5}
}

func (x *PlanListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PlanListResponse) GetPlans() []*FollowupPlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *PlanListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_followup_followup_proto protoreflect.FileDescriptor

const file_followup_followup_proto_rawDesc = "" +
	"\n" +
	"\x17followup/followup.proto\x12\bfollowup\x1a\x13common/common.proto\"\x99\x02\n" +
	"\fFollowupPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12\x1b\n" +
	"\tplan_name\x18\x04 \x01(\tR\bplanName\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x1c\n" +
	"\tfrequency\x18\a \x01(\x05R\tfrequency\x12,\n" +
	"\x05tasks\x18\b \x03(\v2\x16.followup.FollowupTaskR\x05tasks\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"\xc1\x01\n" +
	"\fFollowupTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1f\n" +
	"\vassignee_id\x18\x03 \x01(\tR\n" +
	"assigneeId\x12!\n" +
	"\fexecute_date\x18\x04 \x01(\tR\vexecuteDate\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"\xbe\x01\n" +
	"\x12SatisfactionSurvey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10followup_task_id\x18\x02 \x01(\tR\x0efollowupTaskId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x1a\n" +
	"\bfeedback\x18\x05 \x01(\tR\bfeedback\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"E\n" +
	"\x12ExecuteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\"q\n" +
	"\x0fPlanListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\x94\x01\n" +
	"\x10PlanListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12,\n" +
	"\x05plans\x18\x02 \x03(\v2\x16.followup.FollowupPlanR\x05plans\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page2\xda\x02\n" +
	"\x0fFollowupService\x12<\n" +
	"\n" +
	"CreatePlan\x12\x16.followup.FollowupPlan\x1a\x16.followup.FollowupPlan\x124\n" +
	"\aGetPlan\x12\x11.common.IdRequest\x1a\x16.followup.FollowupPlan\x12C\n" +
	"\vExecuteTask\x12\x1c.followup.ExecuteTaskRequest\x1a\x16.followup.FollowupTask\x12J\n" +
	"\fSubmitSurvey\x12\x1c.followup.SatisfactionSurvey\x1a\x1c.followup.SatisfactionSurvey\x12B\n" +
	"\tListPlans\x12\x19.followup.PlanListRequest\x1a\x1a.followup.PlanListResponseB\x1bZ\x19his-go/api/proto/followupb\x06proto3"

var (
	file_followup_followup_proto_rawDescOnce sync.Once
	file_followup_followup_proto_rawDescData []byte
)

func file_followup_followup_proto_rawDescGZIP() []byte {
	file_followup_followup_proto_rawDescOnce.Do(func() {
		file_followup_followup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_followup_followup_proto_rawDesc), len(file_followup_followup_proto_rawDesc)))
	})
	return file_followup_followup_proto_rawDescData
}

var file_followup_followup_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_followup_followup_proto_goTypes = []any{
	(*FollowupPlan)(nil),        // 0: followup.FollowupPlan
	(*FollowupTask)(nil),        // 1: followup.FollowupTask
	(*SatisfactionSurvey)(nil),  // 2: followup.SatisfactionSurvey
	(*ExecuteTaskRequest)(nil),  // 3: followup.ExecuteTaskRequest
	(*PlanListRequest)(nil),     // 4: followup.PlanListRequest
	(*PlanListResponse)(nil),    // 5: followup.PlanListResponse
	(*common.PageRequest)(nil),  // 6: common.PageRequest
	(*common.BaseResponse)(nil), // 7: common.BaseResponse
	(*common.PageResponse)(nil), // 8: common.PageResponse
	(*common.IdRequest)(nil),    // 9: common.IdRequest
}
var file_followup_followup_proto_depIdxs = []int32{
	1,  // 0: followup.FollowupPlan.tasks:type_name -> followup.FollowupTask
	6,  // 1: followup.PlanListRequest.page:type_name -> common.PageRequest
	7,  // 2: followup.PlanListResponse.base:type_name -> common.BaseResponse
	0,  // 3: followup.PlanListResponse.plans:type_name -> followup.FollowupPlan
	8,  // 4: followup.PlanListResponse.page:type_name -> common.PageResponse
	0,  // 5: followup.FollowupService.CreatePlan:input_type -> followup.FollowupPlan
	9,  // 6: followup.FollowupService.GetPlan:input_type -> common.IdRequest
	3,  // 7: followup.FollowupService.ExecuteTask:input_type -> followup.ExecuteTaskRequest
	2,  // 8: followup.FollowupService.SubmitSurvey:input_type -> followup.SatisfactionSurvey
	4,  // 9: followup.FollowupService.ListPlans:input_type -> followup.PlanListRequest
	0,  // 10: followup.FollowupService.CreatePlan:output_type -> followup.FollowupPlan
	0,  // 11: followup.FollowupService.GetPlan:output_type -> followup.FollowupPlan
	1,  // 12: followup.FollowupService.ExecuteTask:output_type -> followup.FollowupTask
	2,  // 13: followup.FollowupService.SubmitSurvey:output_type -> followup.SatisfactionSurvey
	5,  // 14: followup.FollowupService.ListPlans:output_type -> followup.PlanListResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_followup_followup_proto_init() }
func file_followup_followup_proto_init() {
	if File_followup_followup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_followup_followup_proto_rawDesc), len(file_followup_followup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_followup_followup_proto_goTypes,
		DependencyIndexes: file_followup_followup_proto_depIdxs,
		MessageInfos:      file_followup_followup_proto_msgTypes,
	}.Build()
	File_followup_followup_proto = out.File
	file_followup_followup_proto_goTypes = nil
	file_followup_followup_proto_depIdxs = nil
}
