// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: followup/followup.proto

package followup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "his-go/api/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FollowupService_CreatePlan_FullMethodName   = "/followup.FollowupService/CreatePlan"
	FollowupService_GetPlan_FullMethodName      = "/followup.FollowupService/GetPlan"
	FollowupService_ExecuteTask_FullMethodName  = "/followup.FollowupService/ExecuteTask"
	FollowupService_SubmitSurvey_FullMethodName = "/followup.FollowupService/SubmitSurvey"
	FollowupService_ListPlans_FullMethodName    = "/followup.FollowupService/ListPlans"
)

// FollowupServiceClient is the client API for FollowupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 随访服务
type FollowupServiceClient interface {
	CreatePlan(ctx context.Context, in *FollowupPlan, opts ...grpc.CallOption) (*FollowupPlan, error)
	GetPlan(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*FollowupPlan, error)
	ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (*FollowupTask, error)
	SubmitSurvey(ctx context.Context, in *SatisfactionSurvey, opts ...grpc.CallOption) (*SatisfactionSurvey, error)
	ListPlans(ctx context.Context, in *PlanListRequest, opts ...grpc.CallOption) (*PlanListResponse, error)
}

type followupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowupServiceClient(cc grpc.ClientConnInterface) FollowupServiceClient {
	return &followupServiceClient{cc}
}

func (c *followupServiceClient) CreatePlan(ctx context.Context, in *FollowupPlan, opts ...grpc.CallOption) (*FollowupPlan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowupPlan)
	err := c.cc.Invoke(ctx, FollowupService_CreatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followupServiceClient) GetPlan(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*FollowupPlan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowupPlan)
	err := c.cc.Invoke(ctx, FollowupService_GetPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followupServiceClient) ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (*FollowupTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowupTask)
	err := c.cc.Invoke(ctx, FollowupService_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followupServiceClient) SubmitSurvey(ctx context.Context, in *SatisfactionSurvey, opts ...grpc.CallOption) (*SatisfactionSurvey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SatisfactionSurvey)
	err := c.cc.Invoke(ctx, FollowupService_SubmitSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followupServiceClient) ListPlans(ctx context.Context, in *PlanListRequest, opts ...grpc.CallOption) (*PlanListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanListResponse)
	err := c.cc.Invoke(ctx, FollowupService_ListPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowupServiceServer is the server API for FollowupService service.
// All implementations must embed UnimplementedFollowupServiceServer
// for forward compatibility.
//
// 随访服务
type FollowupServiceServer interface {
	CreatePlan(context.Context, *FollowupPlan) (*FollowupPlan, error)
	GetPlan(context.Context, *common.IdRequest) (*FollowupPlan, error)
	ExecuteTask(context.Context, *ExecuteTaskRequest) (*FollowupTask, error)
	SubmitSurvey(context.Context, *SatisfactionSurvey) (*SatisfactionSurvey, error)
	ListPlans(context.Context, *PlanListRequest) (*PlanListResponse, error)
	mustEmbedUnimplementedFollowupServiceServer()
}

// UnimplementedFollowupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowupServiceServer struct{}

func (UnimplementedFollowupServiceServer) CreatePlan(context.Context, *FollowupPlan) (*FollowupPlan, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedFollowupServiceServer) GetPlan(context.Context, *common.IdRequest) (*FollowupPlan, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlan not implemented")
}
func (UnimplementedFollowupServiceServer) ExecuteTask(context.Context, *ExecuteTaskRequest) (*FollowupTask, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedFollowupServiceServer) SubmitSurvey(context.Context, *SatisfactionSurvey) (*SatisfactionSurvey, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSurvey not implemented")
}
func (UnimplementedFollowupServiceServer) ListPlans(context.Context, *PlanListRequest) (*PlanListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlans not implemented")
}
func (UnimplementedFollowupServiceServer) mustEmbedUnimplementedFollowupServiceServer() {}
func (UnimplementedFollowupServiceServer) testEmbeddedByValue()                         {}

// UnsafeFollowupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowupServiceServer will
// result in compilation errors.
type UnsafeFollowupServiceServer interface {
	mustEmbedUnimplementedFollowupServiceServer()
}

func RegisterFollowupServiceServer(s grpc.ServiceRegistrar, srv FollowupServiceServer) {
	// If the following call panics, it indicates UnimplementedFollowupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowupService_ServiceDesc, srv)
}

func _FollowupService_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowupPlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowupServiceServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowupService_CreatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowupServiceServer).CreatePlan(ctx, req.(*FollowupPlan))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowupService_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowupServiceServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowupService_GetPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowupServiceServer).GetPlan(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowupService_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowupServiceServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowupService_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowupServiceServer).ExecuteTask(ctx, req.(*ExecuteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowupService_SubmitSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatisfactionSurvey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowupServiceServer).SubmitSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowupService_SubmitSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowupServiceServer).SubmitSurvey(ctx, req.(*SatisfactionSurvey))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowupService_ListPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowupServiceServer).ListPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowupService_ListPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowupServiceServer).ListPlans(ctx, req.(*PlanListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowupService_ServiceDesc is the grpc.ServiceDesc for FollowupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "followup.FollowupService",
	HandlerType: (*FollowupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlan",
			Handler:    _FollowupService_CreatePlan_Handler,
		},
		{
			MethodName: "GetPlan",
			Handler:    _FollowupService_GetPlan_Handler,
		},
		{
			MethodName: "ExecuteTask",
			Handler:    _FollowupService_ExecuteTask_Handler,
		},
		{
			MethodName: "SubmitSurvey",
			Handler:    _FollowupService_SubmitSurvey_Handler,
		},
		{
			MethodName: "ListPlans",
			Handler:    _FollowupService_ListPlans_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "followup/followup.proto",
}
