apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: his

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgresql.yaml
  - redis.yaml
  - rabbitmq.yaml
  - nacos.yaml
  - minio.yaml
  - services.yaml
  - nginx.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: his-go
