apiVersion: v1
kind: Secret
metadata:
  name: his-secrets
  namespace: his
type: Opaque
stringData:
  db-password: "change_me_123"
  redis-password: "change_me_456"
  mq-password: "change_me_789"
  minio-secret-key: "change_me_012"
  jwt-private-key: ""
  jwt-public-key: ""
