// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: statistics/statistics.proto

package statistics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatisticsService_GetOperationStats_FullMethodName = "/statistics.StatisticsService/GetOperationStats"
	StatisticsService_GetDeptWorkload_FullMethodName   = "/statistics.StatisticsService/GetDeptWorkload"
	StatisticsService_GetRevenueTrend_FullMethodName   = "/statistics.StatisticsService/GetRevenueTrend"
)

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 统计服务
type StatisticsServiceClient interface {
	GetOperationStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*OperationStats, error)
	GetDeptWorkload(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*DeptWorkloadResponse, error)
	GetRevenueTrend(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*RevenueTrendResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) GetOperationStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*OperationStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStats)
	err := c.cc.Invoke(ctx, StatisticsService_GetOperationStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetDeptWorkload(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*DeptWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeptWorkloadResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetDeptWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetRevenueTrend(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*RevenueTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevenueTrendResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetRevenueTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility.
//
// 统计服务
type StatisticsServiceServer interface {
	GetOperationStats(context.Context, *StatsRequest) (*OperationStats, error)
	GetDeptWorkload(context.Context, *StatsRequest) (*DeptWorkloadResponse, error)
	GetRevenueTrend(context.Context, *StatsRequest) (*RevenueTrendResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatisticsServiceServer struct{}

func (UnimplementedStatisticsServiceServer) GetOperationStats(context.Context, *StatsRequest) (*OperationStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperationStats not implemented")
}
func (UnimplementedStatisticsServiceServer) GetDeptWorkload(context.Context, *StatsRequest) (*DeptWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeptWorkload not implemented")
}
func (UnimplementedStatisticsServiceServer) GetRevenueTrend(context.Context, *StatsRequest) (*RevenueTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevenueTrend not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}
func (UnimplementedStatisticsServiceServer) testEmbeddedByValue()                           {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	// If the following call panics, it indicates UnimplementedStatisticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_GetOperationStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetOperationStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetOperationStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetOperationStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetDeptWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetDeptWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetDeptWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetDeptWorkload(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetRevenueTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetRevenueTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetRevenueTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetRevenueTrend(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statistics.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOperationStats",
			Handler:    _StatisticsService_GetOperationStats_Handler,
		},
		{
			MethodName: "GetDeptWorkload",
			Handler:    _StatisticsService_GetDeptWorkload_Handler,
		},
		{
			MethodName: "GetRevenueTrend",
			Handler:    _StatisticsService_GetRevenueTrend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statistics/statistics.proto",
}
