// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: statistics/statistics.proto

package statistics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 运营统计
type OperationStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalRegistrations int32                  `protobuf:"varint,1,opt,name=total_registrations,json=totalRegistrations,proto3" json:"total_registrations,omitempty"`
	TotalClinicVisits  int32                  `protobuf:"varint,2,opt,name=total_clinic_visits,json=totalClinicVisits,proto3" json:"total_clinic_visits,omitempty"`
	TotalPrescriptions int32                  `protobuf:"varint,3,opt,name=total_prescriptions,json=totalPrescriptions,proto3" json:"total_prescriptions,omitempty"`
	TotalRevenue       float64                `protobuf:"fixed64,4,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TodayRevenue       float64                `protobuf:"fixed64,5,opt,name=today_revenue,json=todayRevenue,proto3" json:"today_revenue,omitempty"`
	InpatientCount     int32                  `protobuf:"varint,6,opt,name=inpatient_count,json=inpatientCount,proto3" json:"inpatient_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OperationStats) Reset() {
	*x = OperationStats{}
	mi := &file_statistics_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStats) ProtoMessage() {}

func (x *OperationStats) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStats.ProtoReflect.Descriptor instead.
func (*OperationStats) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *OperationStats) GetTotalRegistrations() int32 {
	if x != nil {
		return x.TotalRegistrations
	}
	return 0
}

func (x *OperationStats) GetTotalClinicVisits() int32 {
	if x != nil {
		return x.TotalClinicVisits
	}
	return 0
}

func (x *OperationStats) GetTotalPrescriptions() int32 {
	if x != nil {
		return x.TotalPrescriptions
	}
	return 0
}

func (x *OperationStats) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *OperationStats) GetTodayRevenue() float64 {
	if x != nil {
		return x.TodayRevenue
	}
	return 0
}

func (x *OperationStats) GetInpatientCount() int32 {
	if x != nil {
		return x.InpatientCount
	}
	return 0
}

// 科室工作量
type DeptWorkload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeptId        string                 `protobuf:"bytes,1,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	DeptName      string                 `protobuf:"bytes,2,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	VisitCount    int32                  `protobuf:"varint,3,opt,name=visit_count,json=visitCount,proto3" json:"visit_count,omitempty"`
	Revenue       float64                `protobuf:"fixed64,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptWorkload) Reset() {
	*x = DeptWorkload{}
	mi := &file_statistics_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptWorkload) ProtoMessage() {}

func (x *DeptWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptWorkload.ProtoReflect.Descriptor instead.
func (*DeptWorkload) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *DeptWorkload) GetDeptId() string {
	if x != nil {
		return x.DeptId
	}
	return ""
}

func (x *DeptWorkload) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *DeptWorkload) GetVisitCount() int32 {
	if x != nil {
		return x.VisitCount
	}
	return 0
}

func (x *DeptWorkload) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

// 收入趋势
type RevenueTrend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevenueTrend) Reset() {
	*x = RevenueTrend{}
	mi := &file_statistics_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenueTrend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueTrend) ProtoMessage() {}

func (x *RevenueTrend) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueTrend.ProtoReflect.Descriptor instead.
func (*RevenueTrend) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *RevenueTrend) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RevenueTrend) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_statistics_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *StatsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *StatsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type DeptWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Workloads     []*DeptWorkload        `protobuf:"bytes,2,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptWorkloadResponse) Reset() {
	*x = DeptWorkloadResponse{}
	mi := &file_statistics_statistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptWorkloadResponse) ProtoMessage() {}

func (x *DeptWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptWorkloadResponse.ProtoReflect.Descriptor instead.
func (*DeptWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *DeptWorkloadResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DeptWorkloadResponse) GetWorkloads() []*DeptWorkload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type RevenueTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Trends        []*RevenueTrend        `protobuf:"bytes,2,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevenueTrendResponse) Reset() {
	*x = RevenueTrendResponse{}
	mi := &file_statistics_statistics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenueTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueTrendResponse) ProtoMessage() {}

func (x *RevenueTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueTrendResponse.ProtoReflect.Descriptor instead.
func (*RevenueTrendResponse) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{5}
}

func (x *RevenueTrendResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RevenueTrendResponse) GetTrends() []*RevenueTrend {
	if x != nil {
		return x.Trends
	}
	return nil
}

var File_statistics_statistics_proto protoreflect.FileDescriptor

const file_statistics_statistics_proto_rawDesc = "" +
	"\n" +
	"\x1bstatistics/statistics.proto\x12\n" +
	"statistics\x1a\x13common/common.proto\"\x95\x02\n" +
	"\x0eOperationStats\x12/\n" +
	"\x13total_registrations\x18\x01 \x01(\x05R\x12totalRegistrations\x12.\n" +
	"\x13total_clinic_visits\x18\x02 \x01(\x05R\x11totalClinicVisits\x12/\n" +
	"\x13total_prescriptions\x18\x03 \x01(\x05R\x12totalPrescriptions\x12#\n" +
	"\rtotal_revenue\x18\x04 \x01(\x01R\ftotalRevenue\x12#\n" +
	"\rtoday_revenue\x18\x05 \x01(\x01R\ftodayRevenue\x12'\n" +
	"\x0finpatient_count\x18\x06 \x01(\x05R\x0einpatientCount\"\x7f\n" +
	"\fDeptWorkload\x12\x17\n" +
	"\adept_id\x18\x01 \x01(\tR\x06deptId\x12\x1b\n" +
	"\tdept_name\x18\x02 \x01(\tR\bdeptName\x12\x1f\n" +
	"\vvisit_count\x18\x03 \x01(\x05R\n" +
	"visitCount\x12\x18\n" +
	"\arevenue\x18\x04 \x01(\x01R\arevenue\":\n" +
	"\fRevenueTrend\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"H\n" +
	"\fStatsRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"x\n" +
	"\x14DeptWorkloadResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x126\n" +
	"\tworkloads\x18\x02 \x03(\v2\x18.statistics.DeptWorkloadR\tworkloads\"r\n" +
	"\x14RevenueTrendResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x120\n" +
	"\x06trends\x18\x02 \x03(\v2\x18.statistics.RevenueTrendR\x06trends2\xfc\x01\n" +
	"\x11StatisticsService\x12I\n" +
	"\x11GetOperationStats\x12\x18.statistics.StatsRequest\x1a\x1a.statistics.OperationStats\x12M\n" +
	"\x0fGetDeptWorkload\x12\x18.statistics.StatsRequest\x1a .statistics.DeptWorkloadResponse\x12M\n" +
	"\x0fGetRevenueTrend\x12\x18.statistics.StatsRequest\x1a .statistics.RevenueTrendResponseB\x1dZ\x1bhis-go/api/proto/statisticsb\x06proto3"

var (
	file_statistics_statistics_proto_rawDescOnce sync.Once
	file_statistics_statistics_proto_rawDescData []byte
)

func file_statistics_statistics_proto_rawDescGZIP() []byte {
	file_statistics_statistics_proto_rawDescOnce.Do(func() {
		file_statistics_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statistics_statistics_proto_rawDesc), len(file_statistics_statistics_proto_rawDesc)))
	})
	return file_statistics_statistics_proto_rawDescData
}

var file_statistics_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_statistics_statistics_proto_goTypes = []any{
	(*OperationStats)(nil),       // 0: statistics.OperationStats
	(*DeptWorkload)(nil),         // 1: statistics.DeptWorkload
	(*RevenueTrend)(nil),         // 2: statistics.RevenueTrend
	(*StatsRequest)(nil),         // 3: statistics.StatsRequest
	(*DeptWorkloadResponse)(nil), // 4: statistics.DeptWorkloadResponse
	(*RevenueTrendResponse)(nil), // 5: statistics.RevenueTrendResponse
	(*common.BaseResponse)(nil),  // 6: common.BaseResponse
}
var file_statistics_statistics_proto_depIdxs = []int32{
	6, // 0: statistics.DeptWorkloadResponse.base:type_name -> common.BaseResponse
	1, // 1: statistics.DeptWorkloadResponse.workloads:type_name -> statistics.DeptWorkload
	6, // 2: statistics.RevenueTrendResponse.base:type_name -> common.BaseResponse
	2, // 3: statistics.RevenueTrendResponse.trends:type_name -> statistics.RevenueTrend
	3, // 4: statistics.StatisticsService.GetOperationStats:input_type -> statistics.StatsRequest
	3, // 5: statistics.StatisticsService.GetDeptWorkload:input_type -> statistics.StatsRequest
	3, // 6: statistics.StatisticsService.GetRevenueTrend:input_type -> statistics.StatsRequest
	0, // 7: statistics.StatisticsService.GetOperationStats:output_type -> statistics.OperationStats
	4, // 8: statistics.StatisticsService.GetDeptWorkload:output_type -> statistics.DeptWorkloadResponse
	5, // 9: statistics.StatisticsService.GetRevenueTrend:output_type -> statistics.RevenueTrendResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_statistics_statistics_proto_init() }
func file_statistics_statistics_proto_init() {
	if File_statistics_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistics_statistics_proto_rawDesc), len(file_statistics_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistics_statistics_proto_goTypes,
		DependencyIndexes: file_statistics_statistics_proto_depIdxs,
		MessageInfos:      file_statistics_statistics_proto_msgTypes,
	}.Build()
	File_statistics_statistics_proto = out.File
	file_statistics_statistics_proto_goTypes = nil
	file_statistics_statistics_proto_depIdxs = nil
}
