// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: billing/billing.proto

package billing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "his-go/api/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_CreateBill_FullMethodName = "/billing.BillingService/CreateBill"
	BillingService_GetBill_FullMethodName    = "/billing.BillingService/GetBill"
	BillingService_PayBill_FullMethodName    = "/billing.BillingService/PayBill"
	BillingService_RefundBill_FullMethodName = "/billing.BillingService/RefundBill"
	BillingService_ListBills_FullMethodName  = "/billing.BillingService/ListBills"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 收费服务
type BillingServiceClient interface {
	CreateBill(ctx context.Context, in *BillInfo, opts ...grpc.CallOption) (*BillInfo, error)
	GetBill(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*BillInfo, error)
	PayBill(ctx context.Context, in *PayRequest, opts ...grpc.CallOption) (*BillInfo, error)
	RefundBill(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*BillInfo, error)
	ListBills(ctx context.Context, in *BillListRequest, opts ...grpc.CallOption) (*BillListResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) CreateBill(ctx context.Context, in *BillInfo, opts ...grpc.CallOption) (*BillInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillInfo)
	err := c.cc.Invoke(ctx, BillingService_CreateBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetBill(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*BillInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillInfo)
	err := c.cc.Invoke(ctx, BillingService_GetBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) PayBill(ctx context.Context, in *PayRequest, opts ...grpc.CallOption) (*BillInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillInfo)
	err := c.cc.Invoke(ctx, BillingService_PayBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) RefundBill(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*BillInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillInfo)
	err := c.cc.Invoke(ctx, BillingService_RefundBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListBills(ctx context.Context, in *BillListRequest, opts ...grpc.CallOption) (*BillListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillListResponse)
	err := c.cc.Invoke(ctx, BillingService_ListBills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
//
// 收费服务
type BillingServiceServer interface {
	CreateBill(context.Context, *BillInfo) (*BillInfo, error)
	GetBill(context.Context, *common.IdRequest) (*BillInfo, error)
	PayBill(context.Context, *PayRequest) (*BillInfo, error)
	RefundBill(context.Context, *common.IdRequest) (*BillInfo, error)
	ListBills(context.Context, *BillListRequest) (*BillListResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) CreateBill(context.Context, *BillInfo) (*BillInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBill not implemented")
}
func (UnimplementedBillingServiceServer) GetBill(context.Context, *common.IdRequest) (*BillInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBill not implemented")
}
func (UnimplementedBillingServiceServer) PayBill(context.Context, *PayRequest) (*BillInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method PayBill not implemented")
}
func (UnimplementedBillingServiceServer) RefundBill(context.Context, *common.IdRequest) (*BillInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundBill not implemented")
}
func (UnimplementedBillingServiceServer) ListBills(context.Context, *BillListRequest) (*BillListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBills not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_CreateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateBill(ctx, req.(*BillInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetBill(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_PayBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).PayBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_PayBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).PayBill(ctx, req.(*PayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_RefundBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).RefundBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_RefundBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).RefundBill(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListBills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListBills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListBills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListBills(ctx, req.(*BillListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBill",
			Handler:    _BillingService_CreateBill_Handler,
		},
		{
			MethodName: "GetBill",
			Handler:    _BillingService_GetBill_Handler,
		},
		{
			MethodName: "PayBill",
			Handler:    _BillingService_PayBill_Handler,
		},
		{
			MethodName: "RefundBill",
			Handler:    _BillingService_RefundBill_Handler,
		},
		{
			MethodName: "ListBills",
			Handler:    _BillingService_ListBills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing/billing.proto",
}
