// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: billing/billing.proto

package billing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "his-go/api/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 账单信息
type BillInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId      string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	RegistrationId string                 `protobuf:"bytes,3,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	BillNo         string                 `protobuf:"bytes,4,opt,name=bill_no,json=billNo,proto3" json:"bill_no,omitempty"`
	TotalAmount    float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaidAmount     float64                `protobuf:"fixed64,6,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	PayMethod      int32                  `protobuf:"varint,7,opt,name=pay_method,json=payMethod,proto3" json:"pay_method,omitempty"` // 1-现金 2-微信 3-支付宝 4-医保
	Status         int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`                        // 0-待支付 1-已支付 2-已退款 3-已取消
	Details        []*BillDetail          `protobuf:"bytes,9,rep,name=details,proto3" json:"details,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BillInfo) Reset() {
	*x = BillInfo{}
	mi := &file_billing_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillInfo) ProtoMessage() {}

func (x *BillInfo) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillInfo.ProtoReflect.Descriptor instead.
func (*BillInfo) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{0}
}

func (x *BillInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BillInfo) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *BillInfo) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *BillInfo) GetBillNo() string {
	if x != nil {
		return x.BillNo
	}
	return ""
}

func (x *BillInfo) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *BillInfo) GetPaidAmount() float64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *BillInfo) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

func (x *BillInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BillInfo) GetDetails() []*BillDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *BillInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 账单明细
type BillDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BillId        string                 `protobuf:"bytes,2,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	ItemType      int32                  `protobuf:"varint,3,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // 1-挂号费 2-检查费 3-药费 4-治疗费
	ItemName      string                 `protobuf:"bytes,4,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillDetail) Reset() {
	*x = BillDetail{}
	mi := &file_billing_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillDetail) ProtoMessage() {}

func (x *BillDetail) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillDetail.ProtoReflect.Descriptor instead.
func (*BillDetail) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{1}
}

func (x *BillDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BillDetail) GetBillId() string {
	if x != nil {
		return x.BillId
	}
	return ""
}

func (x *BillDetail) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *BillDetail) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *BillDetail) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *BillDetail) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BillDetail) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 支付请求
type PayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BillId        string                 `protobuf:"bytes,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	PayMethod     int32                  `protobuf:"varint,2,opt,name=pay_method,json=payMethod,proto3" json:"pay_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayRequest) Reset() {
	*x = PayRequest{}
	mi := &file_billing_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRequest) ProtoMessage() {}

func (x *PayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRequest.ProtoReflect.Descriptor instead.
func (*PayRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{2}
}

func (x *PayRequest) GetBillId() string {
	if x != nil {
		return x.BillId
	}
	return ""
}

func (x *PayRequest) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

type BillListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageRequest    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillListRequest) Reset() {
	*x = BillListRequest{}
	mi := &file_billing_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillListRequest) ProtoMessage() {}

func (x *BillListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillListRequest.ProtoReflect.Descriptor instead.
func (*BillListRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{3}
}

func (x *BillListRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *BillListRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *BillListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BillListRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *BillListRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type BillListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Bills         []*BillInfo            `protobuf:"bytes,2,rep,name=bills,proto3" json:"bills,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillListResponse) Reset() {
	*x = BillListResponse{}
	mi := &file_billing_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillListResponse) ProtoMessage() {}

func (x *BillListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillListResponse.ProtoReflect.Descriptor instead.
func (*BillListResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{4}
}

func (x *BillListResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *BillListResponse) GetBills() []*BillInfo {
	if x != nil {
		return x.Bills
	}
	return nil
}

func (x *BillListResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_billing_billing_proto protoreflect.FileDescriptor

const file_billing_billing_proto_rawDesc = "" +
	"\n" +
	"\x15billing/billing.proto\x12\abilling\x1a\x13common/common.proto\"\xc4\x02\n" +
	"\bBillInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12'\n" +
	"\x0fregistration_id\x18\x03 \x01(\tR\x0eregistrationId\x12\x17\n" +
	"\abill_no\x18\x04 \x01(\tR\x06billNo\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12\x1f\n" +
	"\vpaid_amount\x18\x06 \x01(\x01R\n" +
	"paidAmount\x12\x1d\n" +
	"\n" +
	"pay_method\x18\a \x01(\x05R\tpayMethod\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12-\n" +
	"\adetails\x18\t \x03(\v2\x13.billing.BillDetailR\adetails\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\xc2\x01\n" +
	"\n" +
	"BillDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\abill_id\x18\x02 \x01(\tR\x06billId\x12\x1b\n" +
	"\titem_type\x18\x03 \x01(\x05R\bitemType\x12\x1b\n" +
	"\titem_name\x18\x04 \x01(\tR\bitemName\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x01R\tunitPrice\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\"D\n" +
	"\n" +
	"PayRequest\x12\x17\n" +
	"\abill_id\x18\x01 \x01(\tR\x06billId\x12\x1d\n" +
	"\n" +
	"pay_method\x18\x02 \x01(\x05R\tpayMethod\"\xab\x01\n" +
	"\x0fBillListRequest\x12'\n" +
	"\x04page\x18\x01 \x01(\v2\x13.common.PageRequestR\x04page\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"\x8f\x01\n" +
	"\x10BillListResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12'\n" +
	"\x05bills\x18\x02 \x03(\v2\x11.billing.BillInfoR\x05bills\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.common.PageResponseR\x04page2\x9e\x02\n" +
	"\x0eBillingService\x122\n" +
	"\n" +
	"CreateBill\x12\x11.billing.BillInfo\x1a\x11.billing.BillInfo\x12/\n" +
	"\aGetBill\x12\x11.common.IdRequest\x1a\x11.billing.BillInfo\x121\n" +
	"\aPayBill\x12\x13.billing.PayRequest\x1a\x11.billing.BillInfo\x122\n" +
	"\n" +
	"RefundBill\x12\x11.common.IdRequest\x1a\x11.billing.BillInfo\x12@\n" +
	"\tListBills\x12\x18.billing.BillListRequest\x1a\x19.billing.BillListResponseB\x1aZ\x18his-go/api/proto/billingb\x06proto3"

var (
	file_billing_billing_proto_rawDescOnce sync.Once
	file_billing_billing_proto_rawDescData []byte
)

func file_billing_billing_proto_rawDescGZIP() []byte {
	file_billing_billing_proto_rawDescOnce.Do(func() {
		file_billing_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)))
	})
	return file_billing_billing_proto_rawDescData
}

var file_billing_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_billing_billing_proto_goTypes = []any{
	(*BillInfo)(nil),            // 0: billing.BillInfo
	(*BillDetail)(nil),          // 1: billing.BillDetail
	(*PayRequest)(nil),          // 2: billing.PayRequest
	(*BillListRequest)(nil),     // 3: billing.BillListRequest
	(*BillListResponse)(nil),    // 4: billing.BillListResponse
	(*common.PageRequest)(nil),  // 5: common.PageRequest
	(*common.BaseResponse)(nil), // 6: common.BaseResponse
	(*common.PageResponse)(nil), // 7: common.PageResponse
	(*common.IdRequest)(nil),    // 8: common.IdRequest
}
var file_billing_billing_proto_depIdxs = []int32{
	1,  // 0: billing.BillInfo.details:type_name -> billing.BillDetail
	5,  // 1: billing.BillListRequest.page:type_name -> common.PageRequest
	6,  // 2: billing.BillListResponse.base:type_name -> common.BaseResponse
	0,  // 3: billing.BillListResponse.bills:type_name -> billing.BillInfo
	7,  // 4: billing.BillListResponse.page:type_name -> common.PageResponse
	0,  // 5: billing.BillingService.CreateBill:input_type -> billing.BillInfo
	8,  // 6: billing.BillingService.GetBill:input_type -> common.IdRequest
	2,  // 7: billing.BillingService.PayBill:input_type -> billing.PayRequest
	8,  // 8: billing.BillingService.RefundBill:input_type -> common.IdRequest
	3,  // 9: billing.BillingService.ListBills:input_type -> billing.BillListRequest
	0,  // 10: billing.BillingService.CreateBill:output_type -> billing.BillInfo
	0,  // 11: billing.BillingService.GetBill:output_type -> billing.BillInfo
	0,  // 12: billing.BillingService.PayBill:output_type -> billing.BillInfo
	0,  // 13: billing.BillingService.RefundBill:output_type -> billing.BillInfo
	4,  // 14: billing.BillingService.ListBills:output_type -> billing.BillListResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_billing_billing_proto_init() }
func file_billing_billing_proto_init() {
	if File_billing_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_billing_proto_goTypes,
		DependencyIndexes: file_billing_billing_proto_depIdxs,
		MessageInfos:      file_billing_billing_proto_msgTypes,
	}.Build()
	File_billing_billing_proto = out.File
	file_billing_billing_proto_goTypes = nil
	file_billing_billing_proto_depIdxs = nil
}
